### Inputs
- name: "Assert inputs of 'slm/init | create_and_store_config.yml'"
  ansible.builtin.assert:
    that:
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)   # Scheme of the Consul instance
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)       # Host of the Consul instance
      - (ENV.CONSUL.PORT.INTERNAL is defined)                                             # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)                     # Token to authenticate with Consul
      - (_cm_name is defined) and (_cm_name|length > 0)                       # Common Name used for the certificate

- name: "Set facts for Consul KV paths"
  ansible.builtin.set_fact:
    __consul_kv_path_crt: certs/traefik/crt
    __consul_kv_path_key: certs/traefik/key
    __consul_kv_path_csr: certs/traefik/csr

- name: "Check certificate in Consul"
  block:
  - name: "Check if certificate exists in Consul at '{{ __consul_kv_path_crt }}'"
    ansible.builtin.set_fact:
      existing_cert: "{{ lookup('community.general.consul_kv', __consul_kv_path_crt, scheme=CONSUL.SCHEME.INTERNAL, host=CONSUL.HOST.INTERNAL, port=CONSUL.PORT.INTERNAL, token=_consul_token) | from_yaml }}"

  - name: "Set facts for certificate generation and import"
    ansible.builtin.set_fact:
      generate_cert: false
      import_cert: false
    when: (existing_cert is defined) and (existing_cert|length > 0) and (existing_cert != "None")

  - name: "Debug message for existing certificate"
    ansible.builtin.debug:
      msg: "Certificate already exists in Consul, skipping generation or import"
    when: generate_cert is defined and import_cert is defined

- name: "Check if certificate is mounted for import"
  block:
  - name: "Check if certificate to import exists"
    ansible.builtin.stat:
      path: /certs/cert.crt
    register: cert_to_import_check

  - name: "Check if private key to import exists"
    ansible.builtin.stat:
      path: /certs/cert.key
    register: key_to_import_check

  - fail:
      msg: "Certificate to import exists, but private key not"
    when: cert_to_import_check.stat.exists and not key_to_import_check.stat.exists

  - ansible.builtin.fail:
      msg: "Private key to import exists, but certificate not"
    when: not cert_to_import_check.stat.exists and key_to_import_check.stat.exists

  - name: "Set facts when certificate and key do not exist"
    ansible.builtin.set_fact:
      import_cert: false
      generate_cert: true
    when:  not cert_to_import_check.stat.exists and not key_to_import_check.stat.exists

  - name: "Set facts when certificate and key exist"
    ansible.builtin.set_fact:
      import_cert: true
      generate_cert: false
    when:  cert_to_import_check.stat.exists and key_to_import_check.stat.exists
  when: generate_cert is not defined and import_cert is not defined

- name: "Generate self-signed certificate"
  block:
  - name: "Create Certificates"
    ansible.builtin.include_role:
      name: eclipse-slm.vault_client
      tasks_from: ca/request_ca
    vars:
      _vault_token: "{{ vault_root_token }}"
      _common_name: "{{ _cm_name }}"
      _pki: "pki_int_{{ _cm_name }}"
      _pki_role: "{{ _cm_name }}"

  - ansible.builtin.set_fact:
      certificate_output:
        certificate: "{{ certificates.certificate }}"
      privatekey_output:
        privatekey: "{{ certificates.private_key }}"
      csr_output:
        csr: "{{ certificates.issuing_ca }}"

  - ansible.builtin.debug:
      msg: "Certificate and private key were generated"
  when: generate_cert == true

- name: "Import certificate from file"
  block:
    - ansible.builtin.set_fact:
        certificate_output:
          certificate: "{{ lookup('file', '/certs/cert.crt') }}"
        privatekey_output:
          privatekey: "{{ lookup('file', '/certs/cert.key') }}"
        csr_output:
          csr: "Certificate was imported and not generated by installer"

    - ansible.builtin.debug:
        msg: "Certificate and private key were imported"
  when: import_cert == true

- name: "Store certificate in Consul"
  community.general.consul_kv:
    scheme: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
    host: "{{ ENV.CONSUL.HOST.INTERNAL }}"
    port: "{{ ENV.CONSUL.PORT.INTERNAL }}"
    token: "{{ _consul_token }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "certs/traefik/crt", value: "{{ certificate_output.certificate }}" }
    - { key: "certs/traefik/key", value: "{{ privatekey_output.privatekey }}" }
    - { key: "certs/traefik/csr", value: "{{ csr_output.csr }}" }
  when: import_cert == true or generate_cert == true

- name: "Convert certificate to format suitable for OIDC discovery CA property required to add Keycloak JWT auth to Vault and Consul"
  block:
  - ansible.builtin.set_fact:
      existing_cert: "{{ certificate_output.certificate }}"
    when: import_cert == true or generate_cert == true

  - ansible.builtin.set_fact:
      oidc_discovery_crt: "{{ existing_cert | regex_replace(' ', '\n') | regex_replace('-----BEGIN\nCERTIFICATE-----', '-----BEGIN CERTIFICATE-----') | regex_replace('-----END\nCERTIFICATE-----', '-----END CERTIFICATE-----') }}"
