---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Cleanup
  hosts: slm
  gather_facts: false # Disable if your role does not rely on facts
  become: true
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Stat target host src dir
      ansible.builtin.stat:
        path: "{{ target_host_src_dir }}"
      register: target_host_src_dir_stat

    - name: Stop and remove Installer container on target host
      when: target_host_src_dir_stat.stat.exists
      community.docker.docker_compose_v2:
        project_src: "{{ target_host_docker_compose_base_dir }}"
        state: absent
        remove_images: all
        remove_volumes: true
        remove_orphans: true

    - name: Remove all running containers and images
      block:
        - name: Get list of all running and stopped containers
          community.docker.docker_host_info:
            containers: true
          register: docker_info

        - name: Stop and remove all existing containers
          when: docker_info.containers | length > 0
          community.docker.docker_container:
            name: "{{ item.Id }}"
            state: absent
            force_kill: true
          loop: "{{ docker_info.containers }}"

        - name: Remove all unused Docker objects (system prune)
          community.docker.docker_prune:
            containers: true
            images: true
            images_filters:
              dangling: false
            networks: true
            volumes: true
            builder_cache: true

    - name: Make sure target host src dir is absent
      ansible.builtin.file:
        path: "{{ target_host_src_dir }}"
        state: absent
