apiVersion: v1
kind: Service
metadata:
  name: service-management
  labels:
    app: service-management
spec:
  type: ClusterIP
  selector:
    app: service-management
  ports:
    - protocol: TCP
      port: {{.Values.slm.service_registry.port}}
      targetPort: 9020