apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-management-database-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/service-management-database-data


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-management-database-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: service-management-database-data-pv

  storageClassName: ""
