services:
  config-exporter:
    image: ghcr.io/eclipse-slm/slm/config-exporter:${SLM_VERSION}
    restart: "no"
    build: .
    environment:
      - CONFIGURE_CORE_PROJECT=true
      - LOCAL_HOSTNAME=${LOCAL_HOSTNAME}
      - SLM_HOSTNAME=${SLM_HOSTNAME}
      - CONSUL_TOKEN=${CONSUL_TOKEN}
      - CONSUL_SCHEME=${CONSUL_SCHEME}
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_Port}
      - LOCAL_JAVA_CA_TRUSTSTORE_PASSWORD=${LOCAL_JAVA_CA_TRUSTSTORE_PASSWORD}
    extra_hosts:
#      - "${SLM_HOSTNAME}:host-gateway"
      - "${SLM_HOSTNAME}:10.17.165.210"
    volumes:
      - "${LOCAL_PROJECT_PATH}:/project"
      - "${LOCAL_JAVA_CA_TRUSTSTORE}:/certs/java/cacerts"
      - "./src:/src"
      - "./templates:/templates"
