apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: {{.Values.vault.port}}
      targetPort: 8200