apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config-root-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-config-root

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config-awx-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-config-awx

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config-awx-jwt-authenticator-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-config-awx-jwt-authenticator

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config-resource-management-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-config-resource-management

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-config-service-management-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/vault-config-service-management

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-data-pv

  storageClassName: ""

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-root-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-config-root-pv

  storageClassName: ""

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-awx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-config-awx-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-awx-jwt-authenticator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-config-awx-jwt-authenticator-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-resource-management-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-config-resource-management-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-config-service-management-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: vault-config-service-management-pv

  storageClassName: ""

---