apiVersion: v1
kind: Pod
metadata:
  name: vault-init
  labels:
    app: vault-init

spec:
  containers:
    - name: vault-init
      image: ghcr.io/eclipse-slm/vault-init:{{ .Values.version}}
      imagePullPolicy: Always
      env:
        - name: KEYCLOAK_AUTHSERVERURL
          value: "http://keycloak:7080/auth"
        - name: VAULT_TOKEN
          value: s.GN32jmokCi9S7O1qM3P5pMLv
      volumeMounts:
        - mountPath: /vault/config/root
          name: vault-config-root-pv
        - mountPath: /vault/config/awx
          name: vault-config-awx-pv
        - mountPath: /vault/config/awx-jwt-authenticator
          name: vault-config-awx-jwt-authenticator-pv
        - mountPath: /vault/config/resource-management
          name: vault-config-resource-management-pv
        - mountPath: /vault/config/service-management
          name: vault-config-service-management-pv

  volumes:
    - name: vault-config-root-pv
      persistentVolumeClaim:
        claimName: vault-config-root-pvc
    - name: vault-config-awx-pv
      persistentVolumeClaim:
        claimName: vault-config-awx-pvc
    - name: vault-config-awx-jwt-authenticator-pv
      persistentVolumeClaim:
        claimName: vault-config-awx-jwt-authenticator-pvc
    - name: vault-config-resource-management-pv
      persistentVolumeClaim:
        claimName: vault-config-resource-management-pvc
    - name: vault-config-service-management-pv
      persistentVolumeClaim:
        claimName: vault-config-service-management-pvc
  restartPolicy: OnFailure