<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>service_management.features.service_deployment.impl</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>
    <parent>
        <groupId>org.eclipse.slm</groupId>
        <artifactId>service_management.features.service_deployment</artifactId>
        <version>${revision}</version>
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>service_management.features.service_deployment.api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>service_management.features.service_offerings.api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>service_management.features.service_offerings.impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>service_management.common.impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>service_management.common.api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>resource_management.service.client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>notification_service.messaging</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>common.consul.client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>common.keycloak.config</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.slm</groupId>
            <artifactId>awx.client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>17.0.1</version>
        </dependency>
    </dependencies>
</project>