apiVersion: v1
kind: Service
metadata:
  name: resource-management
  labels:
    app: resource-management
spec:
  type: ClusterIP
  selector:
    app: resource-management
  ports:
    - protocol: TCP
      port: {{.Values.slm.resource_management.port}}
      targetPort: 9010