- name: "Export configuration"
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Load common config"
      ansible.builtin.set_fact:
        CONFIGURE_CORE_PROJECT: "{{ lookup('env', 'CONFIGURE_CORE_PROJECT') }}"
        LOCAL_HOSTNAME: "{{ lookup('env', 'LOCAL_HOSTNAME') }}"
        SLM_HOSTNAME: "{{ lookup('env', 'SLM_HOSTNAME') }}"

    - name: "Load Consul config"
      ansible.builtin.set_fact:
        consul_scheme: "{{ lookup('env', 'CONSUL_SCHEME') }}"
        consul_host: "{{ lookup('env', 'CONSUL_HOST') }}"
        consul_port: "{{ lookup('env', 'CONSUL_PORT') }}"
        consul_token: "{{ lookup('env', 'CONSUL_TOKEN') }}"

    - name: "Set Spring Profile"
      ansible.builtin.set_fact:
        spring_profile: "{{ lookup('env', 'SPRING_PROFILE', default='dev') }}"

    - name: "Get meta data of SLM node from Consul"
      include_tasks: get_consul_node_meta.yml
      vars:
        _node_name: "SLM"
    - ansible.builtin.set_fact:
        SLM_NODE_META: "{{ node_meta }}"

    - ansible.builtin.set_fact:
        traefik_certificate_crt: "{{ lookup('community.general.consul_kv', 'certs/traefik/crt', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) }}"
        traefik_certificate_key: "{{ lookup('community.general.consul_kv', 'certs/traefik/key', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) }}"
        keycloak_config: "{{ lookup('community.general.consul_kv', 'config/keycloak/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        awx_config: "{{ lookup('community.general.consul_kv', 'config/awx/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        consul_config: "{{ lookup('community.general.consul_kv', 'config/consul/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        vault_config: "{{ lookup('community.general.consul_kv', 'config/vault/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        platform_management_config: "{{ lookup('community.general.consul_kv', 'config/platform_management/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        platform_management_keycloak_config: "{{ lookup('community.general.consul_kv', 'config/platform_management/keycloak', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        resource_management_config: "{{ lookup('community.general.consul_kv', 'config/resource_management/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        resource_management_keycloak_config: "{{ lookup('community.general.consul_kv', 'config/resource_management/keycloak', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        service_management_config: "{{ lookup('community.general.consul_kv', 'config/service_management/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        service_management_keycloak_config: "{{ lookup('community.general.consul_kv', 'config/service_management/keycloak', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        notification_service_config: "{{ lookup('community.general.consul_kv', 'config/notification_service/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        notification_service_keycloak_config: "{{ lookup('community.general.consul_kv', 'config/notification_service/keycloak', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        information_service_config: "{{ lookup('community.general.consul_kv', 'config/information_service/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        information_service_keycloak_config: "{{ lookup('community.general.consul_kv', 'config/information_service/keycloak', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        catalog_service_config: "{{ lookup('community.general.consul_kv', 'config/catalog_service/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        monitoring_config: "{{ lookup('community.general.consul_kv', 'config/monitoring/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"
        minio_config: "{{ lookup('community.general.consul_kv', 'config/minio/data', scheme=consul_scheme, host=consul_host, port=consul_port, token=consul_token) | from_yaml }}"

    - ansible.builtin.set_fact:
        platform_management_external_config:  "{{ platform_management_config  | combine({'database':{'port': platform_db_port}}, recursive=True)      | combine(lookup('template', '../templates/service_external_consul_kv_entry.j2') | from_yaml, recursive=True) }}"
        resource_management_external_config:  "{{ resource_management_config  | combine({'database':{'port': resource_db_port}}, recursive=True)      | combine(lookup('template', '../templates/service_external_consul_kv_entry.j2') | from_yaml, recursive=True) }}"
        service_management_external_config:   "{{ service_management_config   | combine({'database':{'port': service_db_port}}, recursive=True)       | combine(lookup('template', '../templates/service_external_consul_kv_entry.j2') | from_yaml, recursive=True) }}"
        notification_service_external_config: "{{ notification_service_config | combine({'database':{'port': notification_db_port}}, recursive=True)  | combine(lookup('template', '../templates/service_external_consul_kv_entry.j2') | from_yaml, recursive=True) }}"
      vars:
        host: "{{ SLM_HOSTNAME }}"
        resource_db_port: 3310
        service_db_port: 3320
        notification_db_port: 3302
        platform_db_port: 3301

    - name: "Write custom spring profile configs to Consul"
      community.general.consul_kv:
        scheme: "{{ consul_scheme }}"
        host: "{{ consul_host }}"
        port: "{{ consul_port }}"
        token: "{{ consul_token }}"
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        # Notification Service:
        - key: "config/notification_service::{{ spring_profile }}/data"
          value: "{{ notification_service_external_config | to_yaml }}"
        # Platform Management:
        - key: "config/platform_management::{{ spring_profile }}/data"
          value: "{{ platform_management_external_config | to_yaml }}"
        # Resource Management:
        - key: "config/resource_management::{{ spring_profile }}/data"
          value: "{{ resource_management_external_config | to_yaml }}"
        # Service Management:
        - key: "config/service_management::{{ spring_profile }}/data"
          value: "{{ service_management_external_config | to_yaml }}"

    - name: "Trust SLM root CA"
      include_tasks: trust_slm_root_ca.yml
      vars:
        vault_url: "{{ SLM_NODE_META.vault_url }}"

    - ansible.builtin.set_fact:
        service_urls: {}

    - name: "Get service config from Consul"
      include_tasks: discover_consul_service.yml
      vars:
        _service_name: "{{ item.service_name }}"
      loop:
        - service_name: "platform-management"
        - service_name: "platform-management-external"
        - service_name: "resource-management"
        - service_name: "resource-management-external"
        - service_name: "service-management"
        - service_name: "service-management-external"
        - service_name: "notification-service"
        - service_name: "notification-service-external"
        - service_name: "information-service"
        - service_name: "awx"
        - service_name: "auth"
        - service_name: "aas-gui"
        - service_name: "catalog-service"
        - service_name: "minio"

    - debug:
        var: service_urls

    - name: "Ensures /project/_config_generated dir exists"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "/project/_config_generated"
        - "/project/_config_generated/keycloak"
        - "/project/_config_generated/keycloak/notification-service"
        - "/project/_config_generated/keycloak/resource-management"
        - "/project/_config_generated/keycloak/service-management"

    - name: "Copy slm-config"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
       - src: /templates/slm-config.yml
         dest: /project/_config_generated/slm-config.yml

    - name: "Update config in application.yml files"
      include_tasks: update_application_properties.yml
      vars:
        _application_yml_file: "{{ module.application_yml_file }}"
        _app_config: "{{ module.app_config }}"
        _consul_service_name: "{{ module.consul_service_name }}"
      when: CONFIGURE_CORE_PROJECT|default(false)|bool == true
      loop_control:
        loop_var: module
      loop:
        - application_yml_file: /project/notification_service/notification_service.service/notification_service.service.app/src/main/resources/application.yml
          app_config: "{{ notification_service_config }}"
          consul_service_name: "notification-service"
        - application_yml_file: /project/information_service/information_service.service/information_service.service.app/src/main/resources/application.yml
          app_config: "{{ information_service_config }}"
          consul_service_name:
        - application_yml_file: /project/platform_management/platform_management.service/platform_management.service.app/src/main/resources/application.yml
          app_config: "{{ platform_management_config }}"
          consul_service_name: "platform-management"
        - application_yml_file: /project/resource_management/resource_management.service/resource_management.service.app/src/main/resources/application.yml
          app_config: "{{ resource_management_config }}"
          consul_service_name: "resource-management"
        - application_yml_file: /project/resource_management/resource_management.service/resource_management.service.initializer/src/main/resources/application.yml
          app_config: "{{ service_management_config }}"
          consul_service_name:
        - application_yml_file: /project/service_management/service_management.service/service_management.service.app/src/main/resources/application.yml
          app_config: "{{ service_management_config }}"
          consul_service_name: "service-management"
        - application_yml_file: /project/service_management/service_management.service/service_management.service.initializer/src/main/resources/application.yml
          app_config: "{{ service_management_config }}"
          consul_service_name:
        - application_yml_file: /project/catalog/catalog.service/catalog.service.app/src/main/resources/application.yml
          app_config: "{{ catalog_service_config }}"
          consul_service_name:

    - name: "Copy application properties"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: /templates/ui/.env.development
          dest: /project/ui/.env.development
      when: CONFIGURE_CORE_PROJECT|default(false)|bool == true

    - name: "Generate certificate for UI"
      include_tasks: get_vault_pki_cert.yml
      vars:
        _vault_url: "{{ SLM_NODE_META.vault_url }}"
        _vault_token: "{{ vault_config.tokens.root }}"
        _vault_pki_role: "traefik"
        _vault_pki_path: "pki_int_slm"
        _common_name: "{{ SLM_HOSTNAME }}"
        _cert_ttl: "8760h"
        _key_dest: "/project/ui/certs/cert.key"
        _certificate_dest: "/project/ui/certs/cert.crt"
      when: CONFIGURE_CORE_PROJECT|default(false)|bool == true


