- debug:
    var: _app_config
    
- name: Set application-dev.yml path
  ansible.builtin.set_fact:
    _application_dev_yml_file: "{{ _application_yml_file | dirname }}/application-{{ spring_profile }}.yml"

- name: "Copy '{{ _application_yml_file }}' to '{{ _application_dev_yml_file }}'"
  ansible.builtin.copy:
    src: "{{ _application_yml_file }}"
    dest: "{{ _application_dev_yml_file }}"

- name: "Update Consul config in file '{{ _application_dev_yml_file }}'"
  ansible.builtin.lineinfile:
    path: "{{ _application_dev_yml_file }}"
    insertafter: "consul:"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "acl-token: .*"
      line: "  acl-token: {{ _app_config['consul']['acl-token'] }}"
    - regexp: "scheme: .*"
      line: "  scheme: {{ consul_scheme }}"
    - regexp: "host: .*"
      line: "  host: {{ consul_host }}"
    - regexp: "port: .*"
      line: "  port: {{ consul_port }}"

- name: "Update consul service name in file '{{ _application_dev_yml_file }}'"
  when: (_consul_service_name is defined) and (_consul_service_name | length > 0)
  ansible.builtin.lineinfile:
    path: "{{ _application_dev_yml_file }}"
    insertafter : 'consul:'
    regexp: "name: {{ _consul_service_name }}.*"
    line: '    name: {{ _consul_service_name }}-external'

- name: "Check if deployment section exists in '{{ _application_dev_yml_file }}'"
  ansible.builtin.lineinfile:
    path: "{{ _application_dev_yml_file }}"
    regexp: "### Deployment"
    state: absent
  check_mode: yes
  changed_when: false
  register: deployment_section

- name: "Update deployment section in file '{{ _application_dev_yml_file }}'"
  ansible.builtin.lineinfile:
    path: "{{ _application_dev_yml_file }}"
    insertafter: "### Deployment"
    firstmatch: true
    regexp: " hostname:"
    line: "  hostname: {{ LOCAL_HOSTNAME }}"
  when: deployment_section.found
