### Inputs
- name: "Assert inputs of 'keycloak/client | create_child_group_and_assign_user.yml'"
  assert:
    that:
      - (keycloak.url.external is defined) and (keycloak.url.external|length > 0)             # Auth URL of the Keycloak instance
      - (_keycloak_access_token is defined) and (_keycloak_access_token|length > 0)           # Access token to authenticate with Keycloak
      - (_keycloak_realm_name is defined) and (_keycloak_realm_name|length > 0)               # Name of the Keycloak realm where the realm role should be created
      - (_username is defined) and (_username|length > 0)                                     # Username of the user to be assigned to the child group
      - (_keycloak_parent_group_name is defined) and (_keycloak_parent_group_name|length > 0) # Name of the parent group under which the child group should be created
      - (_keycloak_child_group is defined) and (_keycloak_child_group|length > 0)             # Keycloak child group representation to create:
                                                                                              # - name: "child_group_name"
                                                                                              #   description: "Description of child group"

- name: "Get details of top level parent group '{{ _keycloak_parent_group_name }}'"
  uri:
    url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/groups?search={{ _keycloak_parent_group_name }}"
    validate_certs: no
    method: GET
    headers:
      authorization: "Bearer {{ keycloak_access_token }}"
    status_code: 200
  register: output_get_parent_group
- set_fact:
    __keycloak_users_parent_group_id: "{{ output_get_parent_group.json[0].id }}"

- block:
  - name: "Create child group '{{ _keycloak_child_group.name }}' under parent group '{{ _keycloak_parent_group_name }}'"
    include_role:
      name: "keycloak/client"
      tasks_from: groups/create_child_group.yml
    vars:
      _keycloak_access_token: "{{ keycloak_access_token }}"
      _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
      _keycloak_parent_group_id: "{{ __keycloak_users_parent_group_id }}"
      _keycloak_group:
        name: "{{ _keycloak_child_group.name }}"
        description: "_keycloak_child_group.description'"
  - name: "Get details of create child group '{{ _keycloak_child_group.name }}'"
    uri:
      url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/groups?search={{ _keycloak_child_group.name }}"
      validate_certs: no
      method: GET
      headers:
        authorization: "Bearer {{ keycloak_access_token }}"
      status_code: 200
    register: output_get_child_group
  - set_fact:
      __keycloak_child_group_id: "{{ (output_get_child_group.json[0].subGroups | selectattr('name', 'equalto', _keycloak_child_group.name) | list | first).id }}"

- block:
  - name: "Get details of '{{ _username }}'"
    uri:
      url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users?username={{ _username }}"
      validate_certs: no
      method: GET
      headers:
        authorization: "Bearer {{ keycloak_access_token }}"
      status_code: 200
    register: output_get_user

  - set_fact:
      __user_id: "{{ output_get_user.json[0].id }}"
  - name: "Assign user '{{ _username }}' to group '{{ _keycloak_child_group.name }}'"
    uri:
      url: "{{ keycloak.url.external }}/admin/realms/{{ ENV.KEYCLOAK.REALM }}/users/{{ __user_id }}/groups/{{ __keycloak_child_group_id }}"
      validate_certs: no
      method: PUT
      headers:
        authorization: "Bearer {{ keycloak_access_token }}"
      status_code: 204
    register: output_add_user_to_group