---
- name: "MINIO | Assert inputs of 'minio/client | config_minio.yml'"
  ansible.builtin.assert:
    that:
      - (_minio_root_user is defined) and (_minio_root_user|length > 0)
      - (_minio_root_password is defined) and (_minio_root_password|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "MINIO | Download Minio Client"
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
    dest: "/usr/local/bin/mc"
    mode: '0755'
  register: mc_download
  changed_when: mc_download is changed

- name: "MINIO | Check if Minio Client is installed"
  ansible.builtin.command: "mc --version"
  changed_when: false
  failed_when: false

- name: "MINIO | Set secure mc command"
  ansible.builtin.set_fact:
    mc_command: "mc"
    minio_alias: "slm"

- name: "MINIO | Configure minio connection alias"
  ansible.builtin.command: "{{ mc_command }} alias set {{ minio_alias }} {{ minio.url.api.internal }} {{ _minio_root_user }} {{ _minio_root_password }}"
  register: alias_command
  changed_when: false
  failed_when: '"Added `slm` successfully." not in alias_command.stdout'
