apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-targets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/prometheus-targets

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-targets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: prometheus-targets-pv

  storageClassName: ""

