### SERVER - Get Catalog Nodes
GET http://{{host}}:{{consul-port}}/v1/catalog/nodes
Authorization: Bearer {{consul-token}}

### SERVER - Get Checks of Node by NodeName
GET http://{{host}}:{{consul-port}}/v1/health/node/test-node-one
Authorization: Bearer {{consul-token}}

### SERVER - Get Node Services
GET http://{{host}}:{{consul-port}}/v1/catalog/node-services/test-node-one
Authorization: Bearer {{consul-token}}

### SERVER - Register Node
PUT http://{{host}}:{{consul-port}}/v1/catalog/register
Authorization: Bearer {{consul-token}}

{
    "ID": "17c0492c-ac95-48ba-b200-7e7dbbed4ee0",
    "Node": "test-node-one",
    "Address": "192.168.32.20",
    "Datacenter": "fabos"
}

### SERVER - DeRegister Node
PUT http://{{host}}:{{consul-port}}/v1/catalog/deregister
Authorization: Bearer {{consul-token}}

{
    "Node": "test-node-one",
    "Datacenter": "fabos"
}

### AGENT - Get Checks of Agent
GET http://{{host}}:{{consul-agent-port}}/v1/agent/checks

### AGENT - Get Services of Agent
GET http://{{host}}:{{consul-agent-port}}/v1/agent/services

### AGENT - PUT Service on Agent
PUT http://{{host}}:{{consul-agent-port}}/v1/agent/service/register
Authorization: Bearer myroot

{

        "ID": "test-service-id",
        "Name": "test-service",
        "Tags": [
            "test-service-tag"
        ],
        "Meta": {
            "test-service-meta-key": "test-service-meta-value"
        }

}

### AGENT - PUT Gracefully leave and shutdown
PUT http://{{host}}:{{consul-agent-port}}/v1/agent/leave
Authorization: Bearer {{consul-token}}

### AGENT - PUT Force leave
PUT http://{{host}}:{{consul-port}}/v1/agent/force-leave/test-node-one?prune
Authorization: Bearer {{consul-token}}

### AGENT - PUT Join
PUT http://{{host}}:{{consul-port}}/v1/agent/join/test-node-one
Authorization: Bearer {{consul-token}}