/* tslint:disable */
/* eslint-disable */
/**
 * Platform Management
 * REST API of Platform Management
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 * Contact: matthias.schneider@ipa.fraunhofer.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Credential
 */
export interface Credential {
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Credential
     */
    'scopesRaw': Array<string>;
    /**
     * 
     * @type {CredentialData}
     * @memberof Credential
     */
    'data': CredentialData;
}
/**
 * 
 * @export
 * @interface CredentialCreateRequest
 */
export interface CredentialCreateRequest {
    /**
     * 
     * @type {Array<CredentialEntityLinkCreateDTO>}
     * @memberof CredentialCreateRequest
     */
    'entityLinks': Array<CredentialEntityLinkCreateDTO>;
    /**
     * 
     * @type {Credential}
     * @memberof CredentialCreateRequest
     */
    'credential': Credential;
    /**
     * 
     * @type {string}
     * @memberof CredentialCreateRequest
     */
    'fullPathOwnerGroupId': string;
}
/**
 * @type CredentialData
 * @export
 */
export type CredentialData = CredentialDataKeyPair | CredentialDataUsernamePassword;

/**
 * 
 * @export
 * @interface CredentialDataKeyPair
 */
export interface CredentialDataKeyPair extends CredentialData {
    /**
     * 
     * @type {string}
     * @memberof CredentialDataKeyPair
     */
    'privateKey': string;
    /**
     * 
     * @type {string}
     * @memberof CredentialDataKeyPair
     */
    'publicKey': string;
}


/**
 * 
 * @export
 * @interface CredentialDataKeyPairReadDTO
 */
export interface CredentialDataKeyPairReadDTO extends CredentialDataReadDTO {
    /**
     * 
     * @type {string}
     * @memberof CredentialDataKeyPairReadDTO
     */
    'publicKey': string;
}


/**
 * 
 * @export
 * @interface CredentialDataReadDTO
 */
export interface CredentialDataReadDTO {
    /**
     * 
     * @type {CredentialDataType}
     * @memberof CredentialDataReadDTO
     */
    'credentialDataType': CredentialDataType;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const CredentialDataType = {
    UsernamePassword: 'USERNAME_PASSWORD',
    KeyPair: 'KEY_PAIR'
} as const;

export type CredentialDataType = typeof CredentialDataType[keyof typeof CredentialDataType];


/**
 * 
 * @export
 * @interface CredentialDataUsernamePassword
 */
export interface CredentialDataUsernamePassword extends CredentialData {
    /**
     * 
     * @type {string}
     * @memberof CredentialDataUsernamePassword
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof CredentialDataUsernamePassword
     */
    'password': string;
}


/**
 * 
 * @export
 * @interface CredentialDataUsernamePasswordReadDTO
 */
export interface CredentialDataUsernamePasswordReadDTO extends CredentialDataReadDTO {
    /**
     * 
     * @type {string}
     * @memberof CredentialDataUsernamePasswordReadDTO
     */
    'username': string;
}


/**
 * 
 * @export
 * @interface CredentialEntityLinkCreateDTO
 */
export interface CredentialEntityLinkCreateDTO {
    /**
     * 
     * @type {string}
     * @memberof CredentialEntityLinkCreateDTO
     */
    'entityType': string;
    /**
     * 
     * @type {string}
     * @memberof CredentialEntityLinkCreateDTO
     */
    'entityId': string;
}
/**
 * 
 * @export
 * @interface CredentialEntityLinkReadDTO
 */
export interface CredentialEntityLinkReadDTO {
    /**
     * 
     * @type {string}
     * @memberof CredentialEntityLinkReadDTO
     */
    'entityType': string;
    /**
     * 
     * @type {string}
     * @memberof CredentialEntityLinkReadDTO
     */
    'entityId': string;
}
/**
 * 
 * @export
 * @interface CredentialReadDTO
 */
export interface CredentialReadDTO {
    /**
     * 
     * @type {string}
     * @memberof CredentialReadDTO
     */
    'id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialReadDTO
     */
    'scopesRaw': Array<string>;
    /**
     * 
     * @type {CredentialReadDTOData}
     * @memberof CredentialReadDTO
     */
    'data': CredentialReadDTOData;
    /**
     * 
     * @type {Array<CredentialEntityLinkReadDTO>}
     * @memberof CredentialReadDTO
     */
    'entityLinks'?: Array<CredentialEntityLinkReadDTO>;
}
/**
 * @type CredentialReadDTOData
 * @export
 */
export type CredentialReadDTOData = CredentialDataKeyPairReadDTO | CredentialDataUsernamePasswordReadDTO;

/**
 * 
 * @export
 * @interface UserCreateRequest
 */
export interface UserCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserCreateRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateRequest
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateRequest
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateRequest
     */
    'password': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreateRequest
     */
    'isPasswordTemporary': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserCreateRequest
     */
    'email': string;
}

/**
 * CredentialsApi - axios parameter creator
 * @export
 */
export const CredentialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add scopes to credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCredentialScopes: async (credentialId: string, requestBody: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('addCredentialScopes', 'credentialId', credentialId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('addCredentialScopes', 'requestBody', requestBody)
            const localVarPath = `/credentials/{credentialId}/scopes`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create credential
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCredential: async (credentialCreateRequest: CredentialCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialCreateRequest' is not null or undefined
            assertParamExists('createCredential', 'credentialCreateRequest', credentialCreateRequest)
            const localVarPath = `/credentials/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(credentialCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create or update credential
         * @param {string} credentialId 
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdateCredential: async (credentialId: string, credentialCreateRequest: CredentialCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('createOrUpdateCredential', 'credentialId', credentialId)
            // verify required parameter 'credentialCreateRequest' is not null or undefined
            assertParamExists('createOrUpdateCredential', 'credentialCreateRequest', credentialCreateRequest)
            const localVarPath = `/credentials/{credentialId}`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(credentialCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredential: async (credentialId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('deleteCredential', 'credentialId', credentialId)
            const localVarPath = `/credentials/{credentialId}`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete credential entity link
         * @param {string} credentialId 
         * @param {string} entityType 
         * @param {string} entityId 
         * @param {boolean} [deleteIfOrphaned] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredentialEntityLink: async (credentialId: string, entityType: string, entityId: string, deleteIfOrphaned?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('deleteCredentialEntityLink', 'credentialId', credentialId)
            // verify required parameter 'entityType' is not null or undefined
            assertParamExists('deleteCredentialEntityLink', 'entityType', entityType)
            // verify required parameter 'entityId' is not null or undefined
            assertParamExists('deleteCredentialEntityLink', 'entityId', entityId)
            const localVarPath = `/credentials/{credentialId}/links`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)

            if (entityType !== undefined) {
                localVarQueryParameter['entityType'] = entityType;
            }

            if (entityId !== undefined) {
                localVarQueryParameter['entityId'] = entityId;
            }

            if (deleteIfOrphaned !== undefined) {
                localVarQueryParameter['deleteIfOrphaned'] = deleteIfOrphaned;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialById: async (credentialId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('getCredentialById', 'credentialId', credentialId)
            const localVarPath = `/credentials/{credentialId}`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get credentials of entity
         * @param {string} entityId 
         * @param {string} entityType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialsOfEntity: async (entityId: string, entityType: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entityId' is not null or undefined
            assertParamExists('getCredentialsOfEntity', 'entityId', entityId)
            // verify required parameter 'entityType' is not null or undefined
            assertParamExists('getCredentialsOfEntity', 'entityType', entityType)
            const localVarPath = `/credentials/entities/{entityId}`
                .replace(`{${"entityId"}}`, encodeURIComponent(String(entityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)

            if (entityType !== undefined) {
                localVarQueryParameter['entityType'] = entityType;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get credentials of user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialsOfUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/credentials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Link existing credential to entity
         * @param {string} credentialId 
         * @param {CredentialEntityLinkCreateDTO} credentialEntityLinkCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkCredentialToEntity: async (credentialId: string, credentialEntityLinkCreateDTO: CredentialEntityLinkCreateDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('linkCredentialToEntity', 'credentialId', credentialId)
            // verify required parameter 'credentialEntityLinkCreateDTO' is not null or undefined
            assertParamExists('linkCredentialToEntity', 'credentialEntityLinkCreateDTO', credentialEntityLinkCreateDTO)
            const localVarPath = `/credentials/{credentialId}/links`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(credentialEntityLinkCreateDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove scopes from credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCredentialScopes: async (credentialId: string, requestBody: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('removeCredentialScopes', 'credentialId', credentialId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('removeCredentialScopes', 'requestBody', requestBody)
            const localVarPath = `/credentials/{credentialId}/scopes`
                .replace(`{${"credentialId"}}`, encodeURIComponent(String(credentialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CredentialsApi - functional programming interface
 * @export
 */
export const CredentialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CredentialsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add scopes to credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addCredentialScopes(credentialId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.addCredentialScopes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create credential
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCredential(credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCredential(credentialCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.createCredential']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create or update credential
         * @param {string} credentialId 
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdateCredential(credentialId: string, credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdateCredential(credentialId, credentialCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.createOrUpdateCredential']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCredential(credentialId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCredential(credentialId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.deleteCredential']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete credential entity link
         * @param {string} credentialId 
         * @param {string} entityType 
         * @param {string} entityId 
         * @param {boolean} [deleteIfOrphaned] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCredentialEntityLink(credentialId: string, entityType: string, entityId: string, deleteIfOrphaned?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCredentialEntityLink(credentialId, entityType, entityId, deleteIfOrphaned, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.deleteCredentialEntityLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCredentialById(credentialId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CredentialReadDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCredentialById(credentialId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.getCredentialById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get credentials of entity
         * @param {string} entityId 
         * @param {string} entityType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCredentialsOfEntity(entityId: string, entityType: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CredentialReadDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCredentialsOfEntity(entityId, entityType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.getCredentialsOfEntity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get credentials of user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCredentialsOfUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CredentialReadDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCredentialsOfUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.getCredentialsOfUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Link existing credential to entity
         * @param {string} credentialId 
         * @param {CredentialEntityLinkCreateDTO} credentialEntityLinkCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async linkCredentialToEntity(credentialId: string, credentialEntityLinkCreateDTO: CredentialEntityLinkCreateDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.linkCredentialToEntity(credentialId, credentialEntityLinkCreateDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.linkCredentialToEntity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove scopes from credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeCredentialScopes(credentialId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CredentialsApi.removeCredentialScopes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CredentialsApi - factory interface
 * @export
 */
export const CredentialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CredentialsApiFp(configuration)
    return {
        /**
         * 
         * @summary Add scopes to credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addCredentialScopes(credentialId, requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create credential
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCredential(credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createCredential(credentialCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create or update credential
         * @param {string} credentialId 
         * @param {CredentialCreateRequest} credentialCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdateCredential(credentialId: string, credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createOrUpdateCredential(credentialId, credentialCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredential(credentialId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCredential(credentialId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete credential entity link
         * @param {string} credentialId 
         * @param {string} entityType 
         * @param {string} entityId 
         * @param {boolean} [deleteIfOrphaned] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredentialEntityLink(credentialId: string, entityType: string, entityId: string, deleteIfOrphaned?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCredentialEntityLink(credentialId, entityType, entityId, deleteIfOrphaned, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get credential by id
         * @param {string} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialById(credentialId: string, options?: RawAxiosRequestConfig): AxiosPromise<CredentialReadDTO> {
            return localVarFp.getCredentialById(credentialId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get credentials of entity
         * @param {string} entityId 
         * @param {string} entityType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialsOfEntity(entityId: string, entityType: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<CredentialReadDTO>> {
            return localVarFp.getCredentialsOfEntity(entityId, entityType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get credentials of user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCredentialsOfUser(options?: RawAxiosRequestConfig): AxiosPromise<Array<CredentialReadDTO>> {
            return localVarFp.getCredentialsOfUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Link existing credential to entity
         * @param {string} credentialId 
         * @param {CredentialEntityLinkCreateDTO} credentialEntityLinkCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkCredentialToEntity(credentialId: string, credentialEntityLinkCreateDTO: CredentialEntityLinkCreateDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.linkCredentialToEntity(credentialId, credentialEntityLinkCreateDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove scopes from credential
         * @param {string} credentialId 
         * @param {Array<string>} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeCredentialScopes(credentialId, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CredentialsApi - object-oriented interface
 * @export
 * @class CredentialsApi
 * @extends {BaseAPI}
 */
export class CredentialsApi extends BaseAPI {
    /**
     * 
     * @summary Add scopes to credential
     * @param {string} credentialId 
     * @param {Array<string>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public addCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).addCredentialScopes(credentialId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create credential
     * @param {CredentialCreateRequest} credentialCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public createCredential(credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).createCredential(credentialCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create or update credential
     * @param {string} credentialId 
     * @param {CredentialCreateRequest} credentialCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public createOrUpdateCredential(credentialId: string, credentialCreateRequest: CredentialCreateRequest, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).createOrUpdateCredential(credentialId, credentialCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete credential by id
     * @param {string} credentialId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public deleteCredential(credentialId: string, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).deleteCredential(credentialId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete credential entity link
     * @param {string} credentialId 
     * @param {string} entityType 
     * @param {string} entityId 
     * @param {boolean} [deleteIfOrphaned] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public deleteCredentialEntityLink(credentialId: string, entityType: string, entityId: string, deleteIfOrphaned?: boolean, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).deleteCredentialEntityLink(credentialId, entityType, entityId, deleteIfOrphaned, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get credential by id
     * @param {string} credentialId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public getCredentialById(credentialId: string, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).getCredentialById(credentialId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get credentials of entity
     * @param {string} entityId 
     * @param {string} entityType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public getCredentialsOfEntity(entityId: string, entityType: string, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).getCredentialsOfEntity(entityId, entityType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get credentials of user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public getCredentialsOfUser(options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).getCredentialsOfUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Link existing credential to entity
     * @param {string} credentialId 
     * @param {CredentialEntityLinkCreateDTO} credentialEntityLinkCreateDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public linkCredentialToEntity(credentialId: string, credentialEntityLinkCreateDTO: CredentialEntityLinkCreateDTO, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).linkCredentialToEntity(credentialId, credentialEntityLinkCreateDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove scopes from credential
     * @param {string} credentialId 
     * @param {Array<string>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CredentialsApi
     */
    public removeCredentialScopes(credentialId: string, requestBody: Array<string>, options?: RawAxiosRequestConfig) {
        return CredentialsApiFp(this.configuration).removeCredentialScopes(credentialId, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserManagementApi - axios parameter creator
 * @export
 */
export const UserManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add user
         * @param {UserCreateRequest} arg0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (arg0: UserCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'arg0' is not null or undefined
            assertParamExists('createUser', 'arg0', arg0)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)

            if (arg0 !== undefined) {
                for (const [key, value] of Object.entries(arg0)) {
                    localVarQueryParameter[key] = value;
                }
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete user by username
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('deleteUser', 'username', username)
            const localVarPath = `/users/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication spring_oauth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "spring_oauth", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserManagementApi - functional programming interface
 * @export
 */
export const UserManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add user
         * @param {UserCreateRequest} arg0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(arg0: UserCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(arg0, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete user by username
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserManagementApi.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserManagementApi - factory interface
 * @export
 */
export const UserManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary Add user
         * @param {UserCreateRequest} arg0 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(arg0: UserCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createUser(arg0, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete user by username
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(username: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteUser(username, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserManagementApi - object-oriented interface
 * @export
 * @class UserManagementApi
 * @extends {BaseAPI}
 */
export class UserManagementApi extends BaseAPI {
    /**
     * 
     * @summary Add user
     * @param {UserCreateRequest} arg0 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public createUser(arg0: UserCreateRequest, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).createUser(arg0, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete user by username
     * @param {string} username 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public deleteUser(username: string, options?: RawAxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).deleteUser(username, options).then((request) => request(this.axios, this.basePath));
    }
}



