/* tslint:disable */
/* eslint-disable */
/**
 * Platform Management
 * REST API of Platform Management
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 * Contact: matthias.schneider@ipa.fraunhofer.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

