services:

  installer-api:
    image: ghcr.io/eclipse-slm/slm/installer-api:${SLM_VERSION}
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: "${INSTALLER_API_COMMAND}"
    environment:
      SLM_HOSTNAME: ${SLM_HOSTNAME}
      SLM_IP: ${SLM_IP}
      INSTALL_DIRECTORY: ${INSTALL_DIRECTORY}
      ANSIBLE_FORCE_COLOR: "1"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "${INSTALL_DIRECTORY}:/install"
      - "./ansible/files/env.yml:/env/env.yml"
      - "./ansible/files/env.override.yml:/env/env.override.yml"
      - "./ansible:/ansible/installer/src"
      - "./ansible:/ansible/uninstaller/src"
      - "./backend:/app/backend"
    ports:
      - "${INSTALLER_API_EXPOSED_PORT}:8080"
    extra_hosts:
      - "${SLM_HOSTNAME}:host-gateway"

  installer-ui:
    image: ghcr.io/eclipse-slm/slm/installer-ui:${SLM_VERSION}
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - installer-api
