### Inputs
- name: "Assert inputs of 'keycloak/init | main.yml'"
  ansible.builtin.assert:
    that:
      - (keycloak.url.external is defined) and (keycloak.url.external|length > 0)
      - (ENV.KEYCLOAK.ADMIN_USERNAME is defined) and (ENV.KEYCLOAK.ADMIN_USERNAME|length > 0)
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)
      - (ENV.CONSUL.PORT.INTERNAL is defined)
      - (_consul_token is defined) and (_consul_token|length > 0)

- name: "Get config"
  block:
  - name: "Keycloak | Check if config exists in Consul"
    community.general.consul_kv:
      scheme: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
      host: "{{ ENV.CONSUL.HOST.INTERNAL }}"
      port: "{{ ENV.CONSUL.PORT.INTERNAL }}"
      token: "{{ _consul_token }}"
      key: "config/keycloak/data"
    register: keycloak_config_consul

  - name: "Set keycloak_config fact if config exists in Consul"
    ansible.builtin.set_fact:
      keycloak_config: "{{ keycloak_config_consul.data.Value | from_yaml }}"
    when: keycloak_config_consul.data.Value is defined

  - name: "Create Keycloak config"
    when: keycloak_config_consul.data.Value is not defined
    block:
    - name: "Create admin password"
      ansible.builtin.set_fact:
        ENV: "{{ ENV | combine( {
                'KEYCLOAK': { 
                    'ADMIN_PASSWORD': lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) 
                  }
                }, recursive=true) }}"
      when: (ENV.KEYCLOAK.ADMIN_PASSWORD is not defined) or (ENV.KEYCLOAK.ADMIN_PASSWORD | default([]) | length == 0)

    - name: "Create database password"
      ansible.builtin.set_fact:
        ENV: "{{ ENV | combine({
                'KEYCLOAK':{ 
                  'DATABASE': { 
                      'PASSWORD': lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) 
                    }
                  }
                }, recursive=true) }}"
      when: (ENV.KEYCLOAK.DATABASE.PASSWORD is not defined) or (ENV.KEYCLOAK.DATABASE.PASSWORD | default([]) | length == 0)

    - name: "Create database root password"
      ansible.builtin.set_fact:
        ENV: "{{ ENV | combine({
                'KEYCLOAK': { 
                  'DATABASE': { 
                      'ROOT_PASSWORD': lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) 
                    }
                  }
                }, recursive=true) }}"
      when: (ENV.KEYCLOAK.DATABASE.ROOT_PASSWORD is not defined) or (ENV.KEYCLOAK.DATABASE.ROOT_PASSWORD | default([]) | length == 0)

    - name: "Update keycloak_config dictionary and override default values"
      ansible.builtin.set_fact:
        keycloak_config: "{{ keycloak_config | default({}) | combine( lookup('template', 'keycloak_config.j2') | from_yaml, recursive=true) }}"

    - name: "Store Keycloak config in Consul"
      community.general.consul_kv:
        scheme: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
        host: "{{ ENV.CONSUL.HOST.INTERNAL }}"
        port: "{{ ENV.CONSUL.PORT.INTERNAL }}"
        token: "{{ _consul_token }}"
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "config/keycloak/data", value: "{{ keycloak_config | to_yaml }}"  }

- name: "Register Keycloak instance at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: auth
    _service_port: "8080"
    _service_address: "keycloak"
    _http: "{{ keycloak.url.internal }}/health"
    _additional_tags:
      - "keycloak"
      - "exposed"

- name: "Register Keycloak database at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: "{{ ENV.KEYCLOAK.DATABASE.HOST.INTERNAL }}"
    _service_port: "{{ ENV.KEYCLOAK.DATABASE.PORT.INTERNAL }}"
    _service_address: "{{ ENV.KEYCLOAK.DATABASE.HOST.INTERNAL }}"
    _tcp: "{{ ENV.KEYCLOAK.DATABASE.HOST.INTERNAL }}:{{ ENV.KEYCLOAK.DATABASE.PORT.INTERNAL }}"
    _additional_tags:
      - "keycloak"
      - "database"
      - "docker-internal"

- name: "Start Keycloak containers"
  block:
    - name: "Create compose definition from template"
      ansible.builtin.set_fact:
        keycloak_compose: "{{ lookup('template', 'keycloak.yml') }}"

    - name: "Start containers"
      # delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
      community.docker.docker_compose_v2:
        project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
        definition: "{{ keycloak_compose | from_yaml}}"
        state: present
        pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

    - name: "Wait for Keycloak ('{{ keycloak.url.external }}') being up"
      ansible.builtin.uri:
        url: "{{ keycloak.url.external }}"
        validate_certs: false
        status_code: 200
      register: result
      until: result.status == 200
      retries: 120
      delay: 3

- name: "Initialize Keycloak"
  block:
  - name: "Get admin access token"
    ansible.builtin.include_role:
      name: eclipse-slm.keycloak_client
      tasks_from: authentication/get_admin_access_token.yml

  - name: "Create realms"
    ansible.builtin.include_role:
      name: "eclipse-slm.keycloak_client"
      tasks_from: realms/create_realm.yml
    vars:
      _keycloak_access_token: "{{ keycloak_access_token }}"
      _keycloak_realm: "{{ item }}"
    loop: "{{ keycloak_realms }}"

  - name: "Create realm roles"
    ansible.builtin.include_role:
      name: "eclipse-slm.keycloak_client"
      tasks_from: roles/create_realm_role.yml
    vars:
      _keycloak_access_token: "{{ keycloak_access_token }}"
      _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
      _keycloak_realm_role: "{{ item }}"
    loop: "{{ keycloak_realm_roles }}"

  - name: "Create groups"
    ansible.builtin.include_role:
      name: "eclipse-slm.keycloak_client"
      tasks_from: groups/create_group.yml
    vars:
      _keycloak_access_token: "{{ keycloak_access_token }}"
      _keycloak_realm_name: "{{ ENV.KEYCLOAK.REALM }}"
      _keycloak_group: "{{ item }}"
    loop: "{{ keycloak_groups_top_level }}"

- name: "Store resulting compose file"
  ansible.builtin.template:
    src: "keycloak.yml"
    dest: "{{ _store_compose_dir | regex_replace('/+$', '') }}/keycloak.yml"
  when: (_store_compose_dir is defined) and (_store_compose_dir|length > 0)
