apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-database-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/catalog-database-data


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-database-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/catalog-database-data


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-database-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: catalog-database-data-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-database-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: catalog-database-config-pv

  storageClassName: ""

