apiVersion: v1
kind: Service
metadata:
  name: catalog-database
  labels:
    app: catalog-database
spec:
  type: ClusterIP
  selector:
    app: catalog-database
  ports:
    - name: internal
      protocol: TCP
      port: {{.Values.catalog.service.database_port}}
      targetPort: 3306
    - name: external
      protocol: TCP
      port: 4406
      targetPort: 3306
