apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  type: ClusterIP
  selector:
    app: consul
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
