apiVersion: v1
kind: Pod
metadata:
  name: consul-init
  labels:
    app: consul-init
spec:

  containers:
    - name: consul-init
      image:
        ghcr.io/eclipse-slm/consul-init:{{ .Values.version }}
      imagePullPolicy: Always
      env:
        - name: KEYCLOAK_AUTHSERVERURL
          value: "http://keycloak:{{ .Values.keycloak.port}}/auth"
      volumeMounts:
        - name: consul-master-token
          mountPath: /config/consul/root/

  volumes:
    - name: consul-master-token
      secret:
        secretName: consul-secret
        items:
          - key: consul-master-token
            path:  consul_master_token

  restartPolicy: OnFailure
