apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/consul-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config-root-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/consul-config-root

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config-awx-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/consul-config-awx

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config-resource-management-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/consul-config-resource-management

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config-service-management-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/consul-config-service-management

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-data-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config-root-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-config-root-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config-awx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-config-awx-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config-resource-management-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-config-resource-management-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-config-service-management-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-config-service-management-pv

  storageClassName: ""

---