apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/consul-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: consul-data-pv

  storageClassName: ""
