apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  type: ClusterIP
  selector:
    app: consul
  ports:
    - protocol: TCP
      port: {{ .Values.slm.consul.port}}
      targetPort: 8500
