apiVersion: v1
kind: Secret
metadata:
  name: consul-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  "consul-secret" ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $consulMasterToken := (get $secretData "consul-master-token") | default (randAlphaNum 32 | b64enc) }}
  # Encoded value: echo -n 'secret'|base64
  consul-master-token: {{ $consulMasterToken }}