- ansible.builtin.assert:
    that:
      - (awx.url.internal is defined) and (awx.url.internal|length > 0)
      - (awx_username is defined) and (awx_username|length > 0)
      - (awx_password is defined) and (awx_password|length > 0)
      - (awx_organization_name is defined) and (awx_organization_name|length > 0)

- name: "Get organizations"
  ansible.builtin.uri:
    url: "{{ awx.url.internal }}/api/v2/organizations"
    method: GET
    force_basic_auth: true
    url_username: "{{ awx_username }}"
    url_password: "{{ awx_password }}"
    status_code: 200
  register: output_get_organizations

- name: "Set awx_organization fact for organization '{{ awx_organization_name }}'"
  ansible.builtin.set_fact:
    awx_organization: "{{ output_get_organizations.json.results | json_query(filter) | first }}"
  vars:
    filter: "[?name=='{{ awx_organization_name }}']"
