---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: slm
  gather_facts: true # Disable if your role does not rely on facts
  become: true
  pre_tasks:
    - name: Apply roles
      ansible.builtin.include_role:
        name: "{{ item.role }}"
        tasks_from: "{{ item.tasks_from | default('main') }}"
      loop:
        - role: eclipse.slm.env
        - role: eclipse.slm.env
          tasks_from: write_hosts
        - role: ../../../consul
          tasks_from: start
  tasks:
    - name: Apply role under test
      ansible.builtin.include_role:
        name: ../../../monitoring
      vars:
        _consul_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
        _store_compose_dir: "/install/deployment"
