- name: "Install Service Lifecycle Management"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Include env role from eclipse.slm collection
      ansible.builtin.include_role:
        name: eclipse.slm.env

# Make sure container hostnames are available on host:
    - name: Add Service Hostnames to /etc/hosts if installer running not in container
      when:
        - ansible_facts['virtualization_type'] is defined
        - ansible_facts['virtualization_type'] not in ['docker', 'podman', 'containerd', 'lxc']
      ansible.builtin.include_role:
        name: eclipse.slm.env
        tasks_from: write_hosts
  tasks:
    - name: "Prepare docker registry logins"
      ansible.builtin.set_fact:
        docker_registry_logins: "{{ ENV.DOCKER_IMAGE_REGISTRY_LOGINS | default([]) }}"

    - name: "Login to configured docker registries"
      community.docker.docker_login:
        registry_url: "{{ item.registry_url }}"
        username: "{{ item.username }}"
        password: "{{ item.password }}"
      loop: "{{ docker_registry_logins }}"
      when: >
        ((item.registry_url is defined) and (item.registry_url|length > 0)) and
        ((item.username is defined) and (item.username|length > 0)) and
        ((item.password is defined) and (item.password|length > 0))

    - name: "Create SLM docker network and add installer to it"
      block:
      - name: "Create docker network for SLM"
        community.docker.docker_compose_v2:
          project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
          definition:
            services:
              installer-helper:
                image: hello-world
                networks:
                  default:

      - name: "Add installer to SLM docker network"
        community.docker.docker_network:
          name: "{{ ENV.COMPOSE_PROJECT_NAME }}_default"
          connected:
            - "{{ lookup('ansible.builtin.env', 'HOSTNAME') | default('eclipse-slm-installer', true) }}"
          appends: true
        register: network_add_result
        failed_when:
          - network_add_result is failed
          - "'already exists' not in network_add_result.msg"

      - name: "Remove helper container for network creation"
        community.docker.docker_container:
          name: "{{ ENV.COMPOSE_PROJECT_NAME }}-installer-helper-1"
          state: absent

    - name: Start SLM and Backend Services
      when: item.when | default(true)
      ansible.builtin.include_role:
        name: "{{ item.name }}"
        tasks_from: "{{ item.tasks_from | default(omit) }}"
      vars:
        _consul_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
        _store_compose_dir: "/install/deployment"
        _vault_root_token: "{{ vault_root_token }}"
      loop:
        - { name: "eclipse.slm.vault" }
        - { name: "eclipse.slm.consul",     tasks_from: "start.yml" }
        - { name: "eclipse.slm.traefik" }
        - { name: "keycloak" }
        - { name: "eclipse.slm.vault",      tasks_from: "init_after_keycloak.yml" }
        - { name: "eclipse.slm.consul" }
        - { name: "rabbitmq" }
        - { name: "minio" }
        - { name: "awx" }
        - { name: "aas" }
        - { name: "monitoring" }
        - { name: "discovery" }
        - { name: "irs", when: "{{ ENV.IRS.ENABLED | bool }}" }
        - { name: "slm" }

    - name: "Store resulting environment file"
      ansible.builtin.include_role:
        name: eclipse.slm.utils
        tasks_from: copy_result_compose_env
      vars:
        _consul_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
        _store_env_file: "/install/deployment/.env"

    - name: "Display installation summary"
      ansible.builtin.debug:
        msg: "Eclipse Service Lifecycle Management version '{{ ENV.SLM_VERSION }}' successfully installed: Consul Master Token: {{ ENV.CONSUL.MASTER_TOKEN }} | Install Directory: {{ INSTALL_DIRECTORY }}"
