- name: "Uninstall SLM"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    compose_project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
  pre_tasks:
    - name: "Set environment facts"
      ansible.builtin.set_fact:
        SLM_HOSTNAME: "{{ lookup('ansible.builtin.env', 'SLM_HOSTNAME') }}"
        SLM_IP: "{{ lookup('ansible.builtin.env', 'SLM_IP') }}"
        INSTALL_DIRECTORY: "{{ lookup('ansible.builtin.env', 'INSTALL_DIRECTORY') }}"

    - name: "Assert intputs for uninstall.yml"
      ansible.builtin.assert:
        that:
          - (SLM_HOSTNAME is defined) and (SLM_HOSTNAME | length > 0)
          - (SLM_IP is defined) and (SLM_IP | length > 0)
          - (INSTALL_DIRECTORY is defined) and (INSTALL_DIRECTORY | length > 0)
        fail_msg: "SLM_HOSTNAME, SLM_IP and INSTALL_DIRECTORY must be set as environment variables before running uninstall.yml"

    - name: Include env role from eclipse.slm collection
      ansible.builtin.include_role:
        name: eclipse.slm.env
  tasks:
    - name: Get running containers, volumes and networks
      community.docker.docker_host_info:
        containers: true
        containers_filters:
          label: "com.docker.compose.project={{ compose_project_name }}"
        containers_all: true
        volumes: true
        volumes_filters:
          label: "com.docker.compose.project={{ compose_project_name }}"
        networks: true
      register: docker_info

    - name: Remove containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
        keep_volumes: false
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
      async: 60
      poll: 0
      register: async_loop

    - name: Wait until containers have been removed
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
        mode: status
      retries: 120
      delay: 1
      loop: "{{ async_loop.results }}"
      register: async_loop_jobs
      until: async_loop_jobs.finished

    - name: Remove volumes
      community.docker.docker_volume:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_info.volumes | map(attribute='Name') | list }}"

    - name: Remove network
      community.docker.docker_network:
        name: "{{ compose_project_name }}_default"
        state: absent

    - name: Remove all unused Docker objects (system prune)
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true

    - name: Remove directories of SLM installation
      ansible.builtin.file:
        path: "{{ INSTALL_DIRECTORY }}/{{ item }}"
        state: absent
      with_items:
        - deployment
        - config

    - name: "Display uninstallation success message"
      ansible.builtin.debug:
        msg: "Eclipse Service Lifecycle Management version '{{ ENV.SLM_VERSION }}' successfully uninstalled"
