apiVersion: v1
kind: Service
metadata:
  name: aas-database
  labels:
    app: aas-database
spec:
  type: ClusterIP
  selector:
    app: aas-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
