apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-database-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/aas-database


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aas-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: aas-database-pv

  storageClassName: ""

