apiVersion: v1
kind: Service
metadata:
  name: aas-registry
  labels:
    app: aas-registry
spec:
  type: ClusterIP
  selector:
    app: aas-registry
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
