- name: "Collect additional service definitions"
  ansible.builtin.set_fact:
    additional_service_definitions: "{{ ENV.ADDITIONAL_SERVICES | default({}) | dict2items }}"

- name: "Deploy enabled additional services"
  include_tasks: "deploy_additional_service_entry.yml"
  loop: "{{ additional_service_definitions }}"
  loop_control:
    loop_var: additional_service_definition
  when: additional_service_definition.value.ENABLED | default(false)

