apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-management-database
  labels:
    app: resource-management-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-management-database
  template:
    metadata:
      name: resource-management-database
      labels:
        app: resource-management-database
    spec:
      containers:
        - name: resource-management-database
          image: mariadb:{{ .Values.resource_management.database_version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: KEYCLOAK_AUTHSERVERURL
              value: http://keycloak:{{.Values.keycloak.port}}/auth
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: resource-management-database-mariadb-config
                  key: database-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-management-database-mariadb-secret
                  key: mysql-password
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: resource-management-database-mariadb-config
                  key: database-schema
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-management-database-mariadb-secret
                  key: mysql-root-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: resource-management-database-data-pv

      volumes:

        - name: resource-management-database-data-pv
          persistentVolumeClaim:
            claimName: resource-management-database-data-pvc

      restartPolicy: Always
