apiVersion: v1
kind: Pod
metadata:
  name: resource-management-init
  labels:
    app: resource-management-init

spec:
  containers:
    - name: resource-management-init
      image: ghcr.io/eclipse-slm/slm/resource-management-init:{{ .Values.slm.version}}
      imagePullPolicy: IfNotPresent
      env:
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://keycloak:{{.Values.slm.keycloak.port}}/auth

  restartPolicy: OnFailure
      