apiVersion: v1
kind: Pod
metadata:
  name: resource-management-init
  labels:
    app: resource-management-init

spec:
  containers:
    - name: resource-management-init
      image: ghcr.io/eclipse-slm/slm/resource-management-init:{{ .Values.slm.version}}
      imagePullPolicy: Always
      env:
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://keycloak:{{.Values.slm.keycloak.port}}/auth
        - name: AWX_HOST
          value: "awx-web"
        - name: AWX_PORT
          value: "{{.Values.slm.awx.port_http}}"

  restartPolicy: OnFailure
      