apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-management
  labels:
    app: resource-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-management
  template:
    metadata:
      name: resource-management
      labels:
        app: resource-management
    spec:
      containers:
        - name: resource-management
          image: ghcr.io/eclipse-slm/slm/resource-management:1.3.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
          env:
            - name: KEYCLOAK_AUTHSERVERURL
              value: http://keycloak:{{.Values.keycloak.port}}/auth
            - name: BASYX_AASREGISTRY_URL
              value: http://aas-registry:4000/registry
            - name: BASYX_AASSERVER_URL
              value: http://aas-server:4001/aasServer
            - name: MONITORING_SERVICE_URL
              value: http://monitoring:9080
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "{{.Values.consul.port}}"
            - name: VAULT_HOST
              value: "vault"
            - name: VAULT_PORT
              value: "{{.Values.vault.port}}"
            - name: NOTIFICATIONSERVICE_HOST
              value: "notification-service"
            - name: NOTIFICATION_SERVICE_PORT
              value: "{{.Values.notification_service.port}}"
            - name: AWX_HOST
              value: "awx-web"
            - name: AWX_PORT
              value: "{{.Values.awx.port_http}}"
            - name: AWX_POLLING_INTERVAL_IN_S
              value: "80"

          volumeMounts:
            - mountPath: /app/awx
              name: awx-config-resource-management-pv
            - mountPath: /app/consul
              name: consul-token
            - mountPath: /app/keycloak
              name: keycloak-config-resource-management-pv
            - mountPath: /app/vault
              name: vault-config-resource-management-pv
            - mountPath: /app/database/config
              name: resource-management-database-config-pv

          livenessProbe:
            httpGet:
              port: 9010
              path: /swagger-ui/index.html
            initialDelaySeconds: 180
            periodSeconds: 90
            timeoutSeconds: 10

      volumes:
        - name: awx-config-resource-management-pv
          persistentVolumeClaim:
            claimName: awx-config-resource-management-pvc
        - name: consul-token
          secret:
            secretName: consul-secret
            items:
              - key: consul-master-token
                path: consul_token
        - name: keycloak-config-resource-management-pv
          persistentVolumeClaim:
            claimName: keycloak-config-resource-management-pvc
        - name: vault-config-resource-management-pv
          persistentVolumeClaim:
            claimName: vault-config-resource-management-pvc
        - name: resource-management-database-config-pv
          persistentVolumeClaim:
            claimName: resource-management-database-config-pvc

      restartPolicy: Always
