apiVersion: v1
kind: Service
metadata:
  name: awx-web
  labels:
    app: awx-web
spec:
  type: LoadBalancer
  selector:
    app: awx-web
  ports:
{{/*    - name: "http"*/}}
{{/*      protocol: TCP*/}}
{{/*      port: {{.Values.awx.port_http}}*/}}
{{/*      targetPort: 8052*/}}
    - name: "container"
      protocol: TCP
      port: 8052
      targetPort: 8052

{{/*    - name: "https"*/}}
{{/*      protocol: TCP*/}}
{{/*      port: {{.Values.awx.port_https}}*/}}
{{/*      targetPort: 8053*/}}