{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: awx-jwt-authenticator*/}}
{{/*  annotations:*/}}
{{/*    kubernetes.io/ingress.class: nginx*/}}
{{/*    nginx.ingress.kubernetes.io/rewrite-target: /$2*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - host: slm-awx-service*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /jwt/(.*)*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: awx-jwt-authenticator*/}}
{{/*                port:*/}}
{{/*                  number: 8051*/}}