apiVersion: v1
kind: Service
metadata:
  name: awx-postgres
  labels:
    app: awx-postgres
spec:
  type: ClusterIP
  selector:
    app: awx-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
