apiVersion: v1
kind: Secret
metadata:
  name: awx-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  "awx-secret" ) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{- $awxAdminPassword := (get $secretData "admin-password") | default (randAlphaNum 32 | b64enc) -}}
  {{ if .Values.default_admin_password -}}
    {{- $awxAdminPassword = (get $secretData "admin-password") | default ( .Values.default_admin_password | b64enc) -}}
  {{ end }}
  {{- $awxAdminPassword = ("password" | b64enc) }}

  admin-username: {{ .Values.awx.admin_username | b64enc }}
  # Encoded value: echo -n 'secret'|base64
  admin-password: {{ $awxAdminPassword }}