apiVersion: v1
kind: Service
metadata:
  name: awx-jwt-authenticator
  labels:
    app: awx-jwt-authenticator
spec:
  type: LoadBalancer
  selector:
    app: awx-jwt-authenticator
  ports:
    - name: "http"
      protocol: TCP
      port: 8051
      targetPort: 8051