apiVersion: v1
kind: Pod
metadata:
  name: awx-web
  labels:
    app: awx-web
spec:
      containers:
        - name: awx-web
          image: fabos4ai/slm-awx-web:15.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8052
            - containerPort: 8053

          volumeMounts:
            - name: awx-supervisor-socket-pv
              mountPath: /var/run/supervisor
            - name: awx-rsyslog-socket-pv
              mountPath: /var/run/awx-rsyslog/
            - name: awx-rsyslog-config-pv
              mountPath: /var/lib/awx/rsyslog/
            - name: awx-redis-pv
              mountPath: /var/run/redis
      volumes:
        - name: awx-supervisor-socket-pv
          persistentVolumeClaim:
            claimName: awx-supervisor-socket-pvc
        - name: awx-rsyslog-socket-pv
          persistentVolumeClaim:
            claimName: awx-rsyslog-socket-pvc
        - name: awx-rsyslog-config-pv
          persistentVolumeClaim:
            claimName: awx-rsyslog-config-pvc
        - name: awx-redis-pv
          persistentVolumeClaim:
            claimName: awx-redis-pvc

      restartPolicy: Always
