apiVersion: v1
kind: Pod
metadata:
  name: awx-redis-init
  labels:
    app: awx-redis-init
spec:

  containers:
    - name: awx-redis-init
      image:
        busybox
      env:
        - name: KEYCLOAK_AUTHSERVERURL
          value: "http://keycloak:{{ .Values.keycloak.port}}/auth"
      command: [ "/bin/sh" ]
      args: [ "-c","cd /var/run/redis/ && chmod -R 777 ." ]
      volumeMounts:
        - name: awx-redis-pv
          mountPath: /var/run/redis/

  volumes:
    - name: awx-redis-pv
      persistentVolumeClaim:
        claimName: awx-redis-pvc

  restartPolicy: OnFailure
