apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-redis-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/slm/awx-redis


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: awx-redis-pv

  storageClassName: ""

