apiVersion: v1
kind: Pod
metadata:
  name: awx-task
  labels:
    app: awx-task

spec:
  containers:
    - name: awx-task
      image: ghcr.io/eclipse-slm/awx/awx-task:{{.Values.slm.awx.version}}
      imagePullPolicy: IfNotPresent

      volumeMounts:
        - name: awx-supervisor-socket-pv
          mountPath: /var/run/supervisor
        - name: awx-rsyslog-socket-pv
          mountPath: /var/run/awx-rsyslog/
        - name: awx-rsyslog-config-pv
          mountPath: /var/lib/awx/rsyslog/
        - name: awx-redis-pv
          mountPath: /var/run/redis

  volumes:
    - name: awx-supervisor-socket-pv
      persistentVolumeClaim:
        claimName: awx-supervisor-socket-pvc
    - name: awx-rsyslog-socket-pv
      persistentVolumeClaim:
        claimName: awx-rsyslog-socket-pvc
    - name: awx-rsyslog-config-pv
      persistentVolumeClaim:
        claimName: awx-rsyslog-config-pvc
    - name: awx-redis-pv
      persistentVolumeClaim:
        claimName: awx-redis-pvc

  restartPolicy: Always
