---
- name: "Get config from Consul"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: get_app_config
  vars:
    _app_name: irs

- name: "IRS | Start Information Receiving Service"
  block:
    - name: "IRS | Create compose fact"
      ansible.builtin.set_fact:
        irs_compose: "{{ lookup('template', 'irs.yml') }}"

    - name: "Start containers"
      community.docker.docker_compose_v2:
        project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
        definition: "{{ irs_compose | from_yaml}}"
        state: present
        pull: "{{ ENV.PULL_DOCKER_IMAGES }}"
      register: irs_compose_start_output

- name: "IRS | Register components at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: "{{ item.name }}"
    _service_port: "{{ item.port }}"
    _service_address: "{{ item.service_address }}"
    _additional_tags: "{{ item.additional_tags }}"
  loop:
    - name: irs
      service_address: "{{ ENV.IRS.HOST.INTERNAL }}"
      port: "{{ ENV.IRS.PORT.INTERNAL }}"
      additional_tags:
        - "irs"
        - "exposed"
        - "traefik.http.routers.irs.rule=PathPrefix(`{{ ENV.IRS.PATH.EXTERNAL }}`)"

- name: "Store resulting compose file"
  ansible.builtin.template:
    src: "irs.yml"
    dest: "{{ _store_compose_dir | regex_replace('/+$', '') }}/irs.yml"
  when: (_store_compose_dir is defined) and (_store_compose_dir|length > 0)
