apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-database
  labels:
    app: notification-service-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-database
  template:
    metadata:
      name: notification-service-database
      labels:
        app: notification-service-database
    spec:
      containers:
        - name: notification-service-database
          image: fabos4ai/mariadb:{{ .Values.slm.notification_service.database_version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: KEYCLOAK_AUTHSERVERURL
              value: http://keycloak:{{.Values.slm.keycloak.port}}/auth
            - name: MYSQL_USER
              value: notification-service
            - name: MYSQL_DATABASE
              value: notifications
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: notification-service-database-data-pv
            - mountPath: /config
              name: notification-service-database-config-pv

      volumes:
        - name: notification-service-database-data-pv
          persistentVolumeClaim:
            claimName: notification-service-database-data-pvc
        - name: notification-service-database-config-pv
          persistentVolumeClaim:
            claimName: notification-service-database-config-pvc

      restartPolicy: Always
