apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/eclipse-slm/slm/notification-service:{{ .Values.slm.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: KEYCLOAK_AUTHSERVERURL
              value: http://keycloak:{{.Values.slm.keycloak.port}}
            - name: CONSUL_PORT
              value: "8500"
            - name: VAULT_PORT
              value: "8200"
            - name: NOTIFICATION_SERVICE_PORT
              value: "9001"
            - name: AWX_HOST
              value: "slm-awx-service"
            - name: AWX_PORT
              value: "80"
          volumeMounts:
            - mountPath: /app/awx
              name: awx-config-notification-service-pv
            - mountPath: /app/keycloak
              name: keycloak-config-notification-service-pv
            - mountPath: /app/database/config
              name: notification-service-database-config-pv

      volumes:
        - name: notification-service-database-config-pv
          persistentVolumeClaim:
            claimName: notification-service-database-config-pvc
        - name: awx-config-notification-service-pv
          persistentVolumeClaim:
            claimName: awx-config-notification-service-pvc
        - name: keycloak-config-notification-service-pv
          persistentVolumeClaim:
            claimName: keycloak-config-notification-service-pvc

      restartPolicy: Always
