### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: resource_management_init
  config:
    import: "optional:consul:"
  cloud:
    consul:
      enabled: false
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        acl-token: ${consul.acl-token}
        register: false
        query-passing: false

resource-management:
  scheme: http
  host: localhost
  port: 9010
  path: /resource-management
  url: ${resource-management.scheme}://${resource-management.host}:${resource-management.port}${resource-management.path}
  init-directories: init/
  api-key: your-resource-management-api-key

### Consul
consul:
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: your-consul-acl-token

