package org.eclipse.slm.service_management.service.app.service_offerings;

import com.fasterxml.jackson.core.JsonProcessingException;
import io.swagger.v3.oas.annotations.Operation;
import org.eclipse.slm.common.model.DeploymentType;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingCreateOrUpdateRequest;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingDTOApi;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingGitRepository;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingNotFoundException;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingVersionCreateException;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingVersionNotFoundException;
import org.eclipse.slm.service_management.model.offerings.responses.ServiceOfferingCreateResponse;
import org.eclipse.slm.service_management.model.vendors.exceptions.ServiceVendorNotFoundException;
import org.eclipse.slm.service_management.service.app.service_categories.ServiceCategoryNotFoundException;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;
import java.util.Map;
import java.util.UUID;

public interface ServiceOfferingRestApi {

    @RequestMapping(value = "", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(summary = "Get service offerings")
    ResponseEntity<List<ServiceOfferingDTOApi>> getServiceOfferings(
            @RequestParam(name = "withImage", defaultValue = "false") boolean withImage,
            @RequestParam(name = "filterByServiceVendorId", required = false) UUID serviceVendorIdFilter
    ) throws JsonProcessingException;

    @RequestMapping(value = "/{serviceOfferingId}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(summary = "Get service offering by id")
    ResponseEntity<ServiceOfferingDTOApi> getServiceOfferingById(
            @PathVariable(name = "serviceOfferingId") UUID serviceOfferingId,
            @RequestParam(name = "withImage", defaultValue = "false") boolean withImage
    ) throws ServiceOfferingNotFoundException;

    @RequestMapping(value = "", method = RequestMethod.POST)
    @Operation(summary = "Create new service offering")
    ResponseEntity<ServiceOfferingCreateResponse> createServiceOfferingWithAutoGeneratedId(
            @RequestBody ServiceOfferingCreateOrUpdateRequest serviceOfferingCreateOrUpdateRequest
    ) throws ServiceVendorNotFoundException, ServiceCategoryNotFoundException;

    @RequestMapping(value = "/{serviceOfferingId}", method = RequestMethod.PUT)
    @Operation(summary = "Create new service offering with specified id or update existing one")
    ResponseEntity<ServiceOfferingCreateResponse> createOrUpdateServiceOfferingWithId(
            @PathVariable(name = "serviceOfferingId") UUID serviceOfferingId,
            @RequestBody ServiceOfferingCreateOrUpdateRequest serviceOfferingCreateOrUpdateRequest
    ) throws ServiceVendorNotFoundException, ServiceCategoryNotFoundException;

    @RequestMapping(value = "/{serviceOfferingId}", method = RequestMethod.DELETE)
    @Operation(summary = "Delete service offering")
    ResponseEntity<Void> deleteServiceOffering(
            @PathVariable(name = "serviceOfferingId") UUID serviceOfferingId
    ) throws ServiceOfferingNotFoundException;

    @RequestMapping(value = "/deploymenttypes", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(summary = "Get possible deployment types")
    ResponseEntity<DeploymentType[]> getDeploymentTypes();

    @RequestMapping(value = "/{serviceOfferingId}/cover", method = RequestMethod.GET, produces = MediaType.IMAGE_PNG_VALUE)
    ResponseEntity<String> getServiceOfferingCover(
            @PathVariable(name = "serviceOfferingId") UUID serviceOfferingId
    );

    @RequestMapping(value = "/git", method = RequestMethod.POST)
    @Operation(summary = "Create new service offering from a git repository")
    ResponseEntity<Map<String, UUID>> addServiceOfferingWithAutoGeneratedIdFromGitRepo(
            @RequestBody ServiceOfferingGitRepository serviceOfferingGitRepository
    ) throws ServiceVendorNotFoundException, ServiceOfferingVersionCreateException, ServiceOfferingNotFoundException,
            ServiceCategoryNotFoundException, ServiceOfferingVersionNotFoundException;
}
