package org.eclipse.slm.service_management.service.app.service_offerings;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.eclipse.slm.common.model.DeploymentType;
import org.eclipse.slm.common.utils.objectmapper.ObjectMapperUtils;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingCreateOrUpdateRequest;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingDTOApi;
import org.eclipse.slm.service_management.model.offerings.ServiceOfferingGitRepository;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingNotFoundException;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingVersionCreateException;
import org.eclipse.slm.service_management.model.offerings.exceptions.ServiceOfferingVersionNotFoundException;
import org.eclipse.slm.service_management.model.vendors.exceptions.ServiceVendorNotFoundException;
import org.eclipse.slm.service_management.service.app.service_categories.ServiceCategoryNotFoundException;
import org.eclipse.slm.service_management.model.offerings.responses.ServiceOfferingCreateResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping(ServiceOfferingRestApiConfig.BASE_PATH)
@Tag(name = ServiceOfferingRestApiConfig.TAG)
public class ServiceOfferingRestController implements ServiceOfferingRestApi {

    private static final Logger Log = LoggerFactory.getLogger(ServiceOfferingRestController.class);

    private final ServiceOfferingHandler serviceOfferingHandler;

    public ServiceOfferingRestController(ServiceOfferingHandler serviceOfferingHandler) {
        this.serviceOfferingHandler = serviceOfferingHandler;
    }

    @Override
    public ResponseEntity<List<ServiceOfferingDTOApi>> getServiceOfferings(
            boolean withImage,
            UUID serviceVendorIdFilter
    )
            throws JsonProcessingException {
        var serviceOfferings = this.serviceOfferingHandler.getServiceOfferings(serviceVendorIdFilter);
        for (var serviceOffering : serviceOfferings) {
            if (!withImage) {
                serviceOffering.setCoverImage(null);
            }
        }
        var serviceOfferingsDTOApi = ObjectMapperUtils.mapAll(serviceOfferings, ServiceOfferingDTOApi.class);

        return ResponseEntity.ok(serviceOfferingsDTOApi);
    }

    @Override
    public ResponseEntity<ServiceOfferingDTOApi> getServiceOfferingById(
            UUID serviceOfferingId,
            boolean withImage)
            throws ServiceOfferingNotFoundException {
        var serviceOffering = this.serviceOfferingHandler.getServiceOfferingById(serviceOfferingId);
        if (!withImage) {
            serviceOffering.setCoverImage(null);
        }
        var serviceOfferingDTOApi = ObjectMapperUtils.map(serviceOffering, ServiceOfferingDTOApi.class);

        return ResponseEntity.ok(serviceOfferingDTOApi);
    }

    @Override
    public ResponseEntity<ServiceOfferingCreateResponse> createServiceOfferingWithAutoGeneratedId(
            ServiceOfferingCreateOrUpdateRequest serviceOfferingCreateOrUpdateRequest)
            throws ServiceVendorNotFoundException, ServiceCategoryNotFoundException {
        var serviceOffering = this.serviceOfferingHandler.createServiceOfferingWithAutoGeneratedId(serviceOfferingCreateOrUpdateRequest);

        return ResponseEntity.ok(new ServiceOfferingCreateResponse(serviceOffering));
    }

    @Override
    public ResponseEntity<ServiceOfferingCreateResponse> createOrUpdateServiceOfferingWithId(
            UUID serviceOfferingId,
            ServiceOfferingCreateOrUpdateRequest serviceOfferingCreateOrUpdateRequest)
            throws ServiceVendorNotFoundException, ServiceCategoryNotFoundException {
        serviceOfferingCreateOrUpdateRequest.setId(serviceOfferingId);
        var serviceOffering = this.serviceOfferingHandler.createOrUpdateServiceOfferingWithId(serviceOfferingCreateOrUpdateRequest);

        return ResponseEntity.ok(new ServiceOfferingCreateResponse(serviceOffering));
    }

    @Override
    public @ResponseBody ResponseEntity<Void> deleteServiceOffering(UUID serviceOfferingId)
            throws ServiceOfferingNotFoundException {
        this.serviceOfferingHandler.deleteServiceOfferingById(serviceOfferingId);
        return ResponseEntity.ok().build();
    }

    @Override
    public ResponseEntity<DeploymentType[]> getDeploymentTypes() {
        return ResponseEntity.ok(DeploymentType.values());
    }

    @Override
    public ResponseEntity<String> getServiceOfferingCover(UUID serviceOfferingId) {
        var coverImage = this.serviceOfferingHandler.getServiceOfferingCoverImageAsBase64(serviceOfferingId);
        return ResponseEntity.ok().body(coverImage);
    }

    @Override
    public ResponseEntity<Map<String, UUID>> addServiceOfferingWithAutoGeneratedIdFromGitRepo
            (ServiceOfferingGitRepository serviceOfferingGitRepository)
            throws ServiceVendorNotFoundException, ServiceOfferingVersionCreateException, ServiceOfferingNotFoundException, ServiceCategoryNotFoundException, ServiceOfferingVersionNotFoundException {

        serviceOfferingGitRepository = this.serviceOfferingHandler.addServiceOfferingWithAutoGeneratedIdFromGitRepo(serviceOfferingGitRepository);

        var versionNamesToIds = new HashMap<String, UUID>();
        for (var serviceOfferingVersion : serviceOfferingGitRepository.getServiceOffering().getVersions()) {
            versionNamesToIds.put(serviceOfferingVersion.getVersion(), serviceOfferingVersion.getId());
        }

        return ResponseEntity.ok().body(versionNamesToIds);
    }

}
