apiVersion: v1
kind: Service
metadata:
  name: service-registry-database
  labels:
    app: service-registry-database
spec:
  type: ClusterIP
  selector:
    app: service-registry-database
  ports:
    - name: internal
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: external
      protocol: TCP
      port: 4406
      targetPort: 3306