apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  type: ClusterIP
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: {{.Values.slm.service_registry.port}}
      targetPort: 9020