apiVersion: v1
kind: Pod
metadata:
  name: service-registry-init
  labels:
    app: service-registry-init

spec:
  containers:
    - name: service-registry-init
      image: fabos4ai/slm-service-registry-init:{{ .Values.slm.version}}
      imagePullPolicy: IfNotPresent
      env:
        - name: SERVICEREGISTRY_INITDIRECTORIES
          value: "{{.Values.slm.service_registry.initialization_local_directories}}"
        - name: SERVICEREGISTRY_GITREPOS_URLS
          value: "{{.Values.slm.service_registry.git_check_interval_minutes}}"
        - name: KEYCLOAK_AUTHSERVERURL
          value: http://keycloak:{{.Values.slm.keycloak.port}}/auth

      volumeMounts:
        - mountPath: /app/keycloak
          name: keycloak-config-service-registry-init-pv

  volumes:
    - name: keycloak-config-service-registry-init-pv
      persistentVolumeClaim:
        claimName: keycloak-config-service-registry-init-pvc

  restartPolicy: OnFailure
      