apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      name: service-registry
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: fabos4ai/slm-service-registry:{{ .Values.slm.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9010
          env:
            - name: KEYCLOAK_AUTHSERVERURL
              value: http://keycloak:{{.Values.slm.keycloak.port}}/auth
            - name: BASYX_AASREGISTRY_URL
              value: http://aas-registry:4000/registry
            - name: BASYX_AASSERVER_URL
              value: http://aas-server:4001/aasServer
            - name: MONITORING_SERVICE_URL
              value: http://monitoring:9080
            - name: CONSUL_PORT
              value: "8500"
            - name: VAULT_PORT
              value: "8200"
            - name: NOTIFICATION_SERVICE_PORT
              value: "9001"
            - name: AWX_HOST
              value: "slm-awx-service"
            - name: AWX_PORT
              value: "80"
          volumeMounts:
            - mountPath: /app/awx
              name: awx-config-service-registry-pv
            - mountPath: /app/consul
              name: consul-config-service-registry-pv
            - mountPath: /app/keycloak
              name: keycloak-config-service-registry-pv
            - mountPath: /app/vault
              name: vault-config-service-registry-pv
            - mountPath: /app/database/config
              name: service-registry-database-config-pv

      volumes:
        - name: awx-config-service-registry-pv
          persistentVolumeClaim:
            claimName: awx-config-service-registry-pvc
        - name: consul-config-service-registry-pv
          persistentVolumeClaim:
            claimName: consul-config-service-registry-pvc
        - name: keycloak-config-service-registry-pv
          persistentVolumeClaim:
            claimName: keycloak-config-service-registry-pvc
        - name: vault-config-service-registry-pv
          persistentVolumeClaim:
            claimName: vault-config-service-registry-pvc
        - name: service-registry-database-config-pv
          persistentVolumeClaim:
            claimName: service-registry-database-config-pvc

      restartPolicy: Always
