version: '3'

services:

  vault:
    image: ghcr.io/eclipse-slm/vault:${VAULT_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${VAULT_PORT}:8200"
    networks:
      default:
        aliases:
          - vault
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - vault_config_root:/vault/config/root
      - vault_data:/vault/file
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: export VAULT_ADDR=http://127.0.0.1:8200 && vault status

  vault-init:
    image: ghcr.io/eclipse-slm/vault-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - vault
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://${SLM_HOSTNAME}:${KEYCLOAK_PORT}/auth"
    volumes:
      - vault_config_root:/vault/config/root
      - vault_config_awx:/vault/config/awx
      - vault_config_awx-jwt-authenticator:/vault/config/awx-jwt-authenticator
      - vault_config_resource-registry:/vault/config/resource-registry
      - vault_config_service-registry:/vault/config/service-registry
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

volumes:
  vault_data:
  vault_config_root:
  vault_config_awx:
  vault_config_awx-jwt-authenticator:
  vault_config_resource-registry:
  vault_config_service-registry:
