services:
  irs:
    image: "{{ ENV.IRS.IMAGE }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ ENV.LOGGING_MAX_FILE }}"
        max-size: "{{ ENV.LOGGING_MAX_SIZE }}"
    networks:
      default:
        aliases:
          - irs
    environment:
      SERVER_SERVLET_CONTEXTPATH: "{{ ENV.IRS.PATH.INTERNAL }}"
      APP_CONFIG: '{{ ENV.IRS.CONFIG | to_json }}'