---
- name: "Generate docker-compose file"
  ansible.builtin.set_fact:
    monitoring_compose: "{{ lookup('template', 'monitoring.yml') }}"

- name: "Start containers"
  community.docker.docker_compose_v2:
    project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
    definition: "{{ monitoring_compose | from_yaml}}"
    state: present
    pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

- name: "Store config in Consul"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: create_or_add_config
  vars:
    _app_name: "monitoring"
    _config:
      prometheus:
        scheme: "{{ ENV.MONITORING.PROMETHEUS.SCHEME.INTERNAL }}"
        host: "{{ ENV.MONITORING.PROMETHEUS.HOST.INTERNAL }}"
        port: "{{ ENV.MONITORING.PROMETHEUS.PORT.INTERNAL }}"
      service:
        scheme: "{{ ENV.MONITORING.PROMETHEUS_AAS.SCHEME.INTERNAL }}"
        host: "{{ ENV.MONITORING.PROMETHEUS_AAS.HOST.INTERNAL }}"
        port: "{{ ENV.MONITORING.PROMETHEUS_AAS.PORT.INTERNAL }}"

- name: "Store resulting compose file"
  ansible.builtin.template:
    src: "monitoring.yml"
    dest: "{{ _store_compose_dir | regex_replace('/+$', '') }}/monitoring.yml"
  when: (_store_compose_dir is defined) and (_store_compose_dir|length > 0)

- name: "Register Prometheus instance at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: prometheus
    _service_port: "{{ ENV.MONITORING.PROMETHEUS.PORT.INTERNAL }}"
    _service_address: "{{ ENV.MONITORING.PROMETHEUS.HOST.INTERNAL }}"
    _http: "{{ ENV.MONITORING.PROMETHEUS.SCHEME.INTERNAL }}://{{ ENV.MONITORING.PROMETHEUS.HOST.INTERNAL }}:{{ ENV.MONITORING.PROMETHEUS.PORT.INTERNAL }}/-/healthy"
    _additional_tags:
      - "monitoring"
