version: '3'

services:

  awx-web:
    image: ghcr.io/eclipse-slm/awx/awx-web:${AWX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis
      - awx-redis-init
      - awx-postgres
    ports:
      - "${AWX_PORT_HTTP}:8052"
      - "${AWX_PORT_HTTPS}:8053"
    networks:
      default:
        aliases:
          - awxweb
    user: root
    volumes:
      - awx_supervisor_socket:/var/run/supervisor
      - awx_rsyslog_socket:/var/run/awx-rsyslog/
      - awx_rsyslog_config:/var/lib/awx/rsyslog/
      - awx-redis:/var/run/redis
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8052" ]

  awx-task:
    image: ghcr.io/eclipse-slm/awx/awx-task:${AWX_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis
      - awx-redis-init
      - awx-web
      - awx-postgres
    networks:
      default:
        aliases:
          - awx
    user: root
    volumes:
      - awx_supervisor_socket:/var/run/supervisor
      - awx_rsyslog_socket:/var/run/awx-rsyslog/
      - awx_rsyslog_config:/var/lib/awx/rsyslog/
      - awx-redis:/var/run/redis

  awx-jwt-authenticator:
    image: ghcr.io/eclipse-slm/awx-jwt-authenticator:1.0.0-snapshot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8051/swagger-ui.html" ]
    ports:
      - "8051:8051"
    networks:
      default:
        aliases:
          - awx-jwt-authenticator
    volumes:
      - vault_config_awx-jwt-authenticator:/opt/vault/awx-jwt-authenticator:ro
      - awx_config_jwt-authenticator:/app/awx
      - keycloak_config_awx-jwt-authenticator:/app/keycloak
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  awx-redis:
    image: fabos4ai/awx-redis:${AWX_REDIS_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis-init
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: [ "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - awx-redis:/var/run/redis/
    healthcheck:
      test: [ "CMD", "redis-cli", "-s", "/var/run/redis/redis.sock", "ping" ]

  awx-redis-init:
    image: busybox
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    command: sh -c "cd /var/run/redis/ && chmod -R 777 ."
    volumes:
      - awx-redis:/var/run/redis/

  awx-postgres:
    image: ghcr.io/eclipse-slm/awx/awx-postgres:${AWX_POSTGRES_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      PGUSER: awx
    volumes:
      - "awx_database_data:/var/lib/postgresql/data:Z"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]

  awx-init:
    image: ghcr.io/eclipse-slm/awx/awx-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-web
      - awx-task
      - awx-jwt-authenticator
      - awx-redis
      - awx-redis-init
      - awx-postgres
    volumes:
      - awx_config_notification-service:/config/notification-service
      - awx_config_resource-management:/config/resource-management
      - awx_config_service-management:/config/service-management
      - awx_config_jwt-authenticator:/config/awx-jwt-authenticator
      - consul_config_awx:/config/consul
      - vault_config_awx:/config/vault

volumes:
  awx_database_data:
  awx_supervisor_socket:
  awx_rsyslog_socket:
  awx_rsyslog_config:
  awx-redis:
  awx_config_notification-service:
  awx_config_resource-management:
  awx_config_service-management:
  awx_config_jwt-authenticator:
