version: '3'

services:

  awx:
    user: "0"
    image: ghcr.io/eclipse-slm/awx/awx-task:${AWX_VERSION}
    command: launch_awx.sh
    environment:
      OS: " Operating System: Docker Desktop"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: tower
      MAIN_NODE_TYPE: "${MAIN_NODE_TYPE:-hybrid}"
      RECEPTORCTL_SOCKET: /var/run/awx-receptor/receptor.sock
      CONTROL_PLANE_NODE_COUNT: 1
      EXECUTION_NODE_COUNT: 0
      AWX_LOGGING_MODE: stdout
#      DJANGO_SUPERUSER_PASSWORD: PrXajTWYbthSGyRhqHDO
      DJANGO_SUPERUSER_PASSWORD: password
      UWSGI_MOUNT_PATH: /
      RUN_MIGRATIONS: 1
    links:
      - awx-postgres
      - awx-redis
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis
      - awx-redis-init
      - awx-postgres
    networks:
      default:
        aliases:
          - awxweb
    volumes:
      - awx_supervisor_socket:/var/run/supervisor
      - awx_rsyslog_socket:/var/run/awx-rsyslog/
      - awx_rsyslog_config:/var/lib/awx/rsyslog/
      - awx-redis:/var/run/redis
#      - "redis_socket:/var/run/redis/:rw"
    privileged: true
    tty: true
    ports:
      - "7899-7999:7899-7999"  # sdb-listen
      - "6899:6899"
#      - "8080:8080"  # unused but mapped for debugging
      - "8888:8888"  # jupyter notebook
      - "8013:8013"  # http
      - "8053:8043"  # https
      - "2222:2222"  # receptor foo node
      - "3001:3001"  # used by the UI dev env

  awx-jwt-authenticator:
    image: ghcr.io/eclipse-slm/awx-jwt-authenticator:1.0.0-snapshot
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8051/swagger-ui.html" ]
    ports:
      - "8051:8051"
    environment:
      AWX_PORT: 8013
    networks:
      default:
        aliases:
          - awx-jwt-authenticator
    volumes:
      - vault_config_awx-jwt-authenticator:/opt/vault/awx-jwt-authenticator:ro
      - awx_config_jwt-authenticator:/app/awx
      - keycloak_config_awx-jwt-authenticator:/app/keycloak
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  awx-redis:
    image: ghcr.io/eclipse-slm/awx/redis:6
    entrypoint: [ "redis-server" ]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - awx-redis-init
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: [ "/usr/local/etc/redis/redis.conf" ]
    networks:
      default:
        aliases:
          - awx-redis
    volumes:
      - awx-redis:/var/run/redis/
#      - "redis_socket:/var/run/redis/:rw"
    healthcheck:
      test: [ "CMD", "redis-cli", "-s", "/var/run/redis/redis.sock", "ping" ]

  awx-redis-init:
    image: busybox
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    command: sh -c "cd /var/run/redis/ && chmod -R 777 ."
    volumes:
      - awx-redis:/var/run/redis/

  awx-postgres:
    image: ghcr.io/eclipse-slm/awx/awx-postgres:${AWX_POSTGRES_VERSION}
    command: postgres -c log_destination=stderr -c log_min_messages=info -c log_min_duration_statement=1000 -c max_connections=1024
    restart: unless-stopped
#    ports:
#      - "5432:5432"
    networks:
      default:
        aliases:
          - postgres
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: awx
      POSTGRES_DB: awx
      POSTGRES_PASSWORD: awxpass
    volumes:
      - "awx_database_data:/var/lib/postgresql/data:Z"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]

  awx-init:
    image: ghcr.io/eclipse-slm/awx/awx-init:${SLM_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      AWX_URL: http://awxweb:8013/
    depends_on:
      - awx-jwt-authenticator
      - awx-redis
      - awx-redis-init
      - awx-postgres
    volumes:
      - awx_config_notification-service:/config/notification-service
      - awx_config_resource-management:/config/resource-management
      - awx_config_service-management:/config/service-management
      - awx_config_jwt-authenticator:/config/awx-jwt-authenticator
      - keycloak_config_awx-jwt-authenticator:/config/keycloak
      - consul_config_awx:/config/consul
      - vault_config_awx:/config/vault
      - minio_config_awx:/config/minio

volumes:
  awx_database_data:
  awx_supervisor_socket:
  awx_rsyslog_socket:
  awx_rsyslog_config:
  awx-redis:
  awx_config_notification-service:
  awx_config_resource-management:
  awx_config_service-management:
  awx_config_jwt-authenticator:
