### Inputs
- name: "Assert inputs of 'awx/init | main.yml'"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)
      - (_vault_root_token is defined) and (_vault_root_token|length > 0)
      - (ENV.CONSUL.SCHEME.INTERNAL is defined) and (ENV.CONSUL.SCHEME.INTERNAL|length > 0)
      - (ENV.CONSUL.HOST.INTERNAL is defined) and (ENV.CONSUL.HOST.INTERNAL|length > 0)
      - (ENV.CONSUL.PORT.INTERNAL is defined)
      - (_consul_token is defined) and (_consul_token|length > 0)

### ToDo: Generate separate Consul token for AWX
- name: "AWX | Set AWX Consul token"
  ansible.builtin.set_fact:
    _awx_consul_token: "{{ _consul_token }}"

- name: "AWX | Disable Apparmor for rsyslogd"
  when:
    - (ansible_facts['distribution'] is defined) and (ansible_facts['distribution'] == "Ubuntu")
    - (ansible_facts['distribution_version'] is defined) and (ansible_facts['distribution_version'] is version('24.04', '>='))
    - (ansible_facts['virtualization_type'] is defined) and (ansible_facts['virtualization_type'] != "docker")
  block:
    - name: "AWX | Disable AppArmor for rsyslogd"
      ansible.builtin.file:
        src: /etc/apparmor.d/usr.sbin.rsyslogd
        dest: /etc/apparmor.d/disable/usr.sbin.rsyslogd
        state: link
        force: true

    - name: "AWX | Remove AppArmor profile for rsyslogd"
      ansible.builtin.command: "apparmor_parser -R /etc/apparmor.d/usr.sbin.rsyslogd"
      changed_when: false
      failed_when: false


- name: "Store AWX config in Consul"
  block:
    - name: "AWX | Check if config exists in Consul"
      community.general.consul_kv:
        scheme: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
        host: "{{ ENV.CONSUL.HOST.INTERNAL }}"
        port: "{{ ENV.CONSUL.PORT.INTERNAL }}"
        token: "{{ _consul_token }}"
        key: "config/awx/data"
      register: awx_config_consul_response

    - name: "AWX | Set app configs fact"
      ansible.builtin.set_fact:
        app_configs: "{{ app_configs | default({}) | combine(
        { 
          'awx': awx_config_consul_response.data.Value | from_yaml
        }, recursive=true) }}"
      when: awx_config_consul_response.data.Value is defined

    - name: "AWX | Update config dictionary and override default values"
      ansible.builtin.set_fact:
        app_configs: "{{ app_configs | default({}) | combine(
          { 
            'awx': {
              'scheme': ENV.AWX.SCHEME.INTERNAL,
              'host': ENV.AWX.HOST.INTERNAL,
              'port': ENV.AWX.PORT.INTERNAL,
              'consul': {
                'token': _awx_consul_token | b64encode
              }
            }
          }, recursive=true) }}"

    - name: "AWX | Create passwords"
      block:
      - name: "AWX | Create AWX admin password"
        ansible.builtin.set_fact:
          ENV: "{{ ENV | combine({
                  'AWX': {
                    'ENV.ADMIN_PASSWORD': lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) 
                    }
                  }, recursive=true) }}"
        when: (ENV.AWX.ADMIN_PASSWORD is not defined) or (ENV.AWX.ADMIN_PASSWORD | length == 0)

      - name: "AWX | Update config dictionary and override default values"
        when: (app_configs.awx.users.admin.password is not defined) or (app_configs.awx.users.admin.password | length == 0)
        ansible.builtin.set_fact:
          app_configs: "{{ app_configs | default({}) | combine(
            { 
              'awx': {
                'users': { 
                  'admin': {
                    'username': 'admin',
                    'password': ENV.AWX.ADMIN_PASSWORD
                  }
                }
              }
            }, recursive=true) }}"

      - name: "AWX | Create AWX JWT Authenticator password"
        when: (app_configs.awx.users.jwt_authenticator.password is not defined) or (app_configs.awx.users.jwt_authenticator.password | length == 0)
        ansible.builtin.set_fact:
          awx_jwt_authenticator_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"

      - name: "AWX | Update config dictionary and override default values"
        when: (app_configs.awx.users.jwt_authenticator.password is not defined) or (app_configs.awx.users.jwt_authenticator.password | length == 0)
        ansible.builtin.set_fact:
          app_configs: "{{ app_configs | default({}) | combine(
            { 
              'awx': {
                'users': {
                  'jwt_authenticator': {
                    'username': 'awx_jwt_authenticator',
                    'password': awx_jwt_authenticator_password
                  }
                }
              }
            }, recursive=true) }}"

    - name: "AWX | Store AWX config in Consul"
      community.general.consul_kv:
        scheme: "{{ ENV.CONSUL.SCHEME.INTERNAL }}"
        host: "{{ ENV.CONSUL.HOST.INTERNAL }}"
        port: "{{ ENV.CONSUL.PORT.INTERNAL }}"
        token: "{{ _consul_token }}"
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "config/awx/data", value: "{{ app_configs.awx | to_yaml }}" }

    - name: "AWX | Create MINIO password"
      when: (app_configs.awx.minio is not defined)
      ansible.builtin.include_tasks: awx_minio_create_credentials.yml
      vars:
        _app_name: "awx"

    - name: "AWX | Decode Consul token"
      ansible.builtin.set_fact:
        app_configs: "{{ app_configs | combine(
          { 
            'awx': {
              'consul': {
                'token': app_configs.awx.consul.token
              }
            }
          }, recursive=true) }}"

- name: "Create AWX JWT Authenticator config"
  ansible.builtin.include_tasks: awx_jwt_authenticator_create_config.yml
  vars:
    _awx_jwt_authenticator_username: "{{ app_configs.awx.users.jwt_authenticator.username }}"
    _awx_jwt_authenticator_password: "{{ app_configs.awx.users.jwt_authenticator.password }}"

- name: "Start AWX"
  block:
    - name: "Create compose definition from template"
      ansible.builtin.set_fact:
        awx_compose: "{{ lookup('template', 'awx.yml') }}"

    - name: "Start AWX containers"
      # delegate_to: '{{ ENV.DEPLOYMENT_HOST_HOSTNAME }}'
      community.docker.docker_compose_v2:
        project_name: "{{ ENV.COMPOSE_PROJECT_NAME }}"
        definition: "{{ awx_compose | from_yaml}}"
        state: present
        pull: "{{ ENV.PULL_DOCKER_IMAGES }}"

    - name: "Wait for AWX ('{{ awx.url.internal }}') being up"
      ansible.builtin.uri:
        url: "{{ awx.url.internal }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 120
      delay: 3

- name: "Init AWX"
  ansible.builtin.include_tasks: awx_init.yml
  vars:
    _awx_admin_username: "{{ app_configs.awx.users.admin.username }}"
    _awx_admin_password: "{{ app_configs.awx.users.admin.password }}"

- name: "Init AWX JWT Authenticator"
  ansible.builtin.include_tasks: awx_jwt_authenticator_init.yml
  vars:
    _awx_admin_username: "{{ app_configs.awx.users.admin.username }}"
    _awx_admin_password: "{{ app_configs.awx.users.admin.password }}"
    _awx_jwt_authenticator_username: "{{ app_configs.awx.users.jwt_authenticator.username }}"
    _awx_jwt_authenticator_password: "{{ app_configs.awx.users.jwt_authenticator.password }}"

- name: "Store resulting compose file"
  when: (_store_compose_dir is defined) and (_store_compose_dir|length > 0)
  ansible.builtin.template:
    src: "awx.yml"
    dest: "{{ _store_compose_dir | regex_replace('/+$', '') }}/awx.yml"

- name: "Register AWX instance at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: awx
    _service_port: "{{ ENV.AWX.PORT.INTERNAL }}"
    _service_address: "{{ ENV.AWX.HOST.INTERNAL }}"
    _http: "{{ awx.url.internal }}"
    _additional_tags:
      - "awx"
      - "exposed"

- name: "Register AWX database at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: awx-postgres
    _service_port: "5432"
    _service_address: "awx-postgres"
    _tcp: "awx-postgres:5432"
    _additional_tags:
      - "awx"
      - "database"
      - "docker-internal"
