### Get Token from Keycloak
POST http://{{host}}:7080/auth/realms/fabos/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=fabos&password=password&client_id=ui

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("auth_token", response.body.access_token);
%}

### Get all profiler
GET http://{{host}}:9010/resources/profiler
Authorization: Bearer {{auth_token}}

### Create profiler
POST http://{{host}}:9010/resources/profiler
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "ansible-facts",
  "action": {
    "actionClass": "AwxAction",
    "actionType": "RUN",
    "awxRepo": "https://github.com/FabOS-AI/fabos-slm-dc-dummy",
    "awxBranch": "main",
    "playbook": "install.yml"
  }
}

### Get one profiler
GET http://{{host}}:9010/resources/profiler/{{profiler-id}}
Authorization: Bearer {{auth_token}}

### Run one profiler
POST http://{{host}}:9010/resources/profiler/{{profiler-id}}/execute
Authorization: Bearer {{auth_token}}

### Delete one profiler
DELETE http://{{host}}:9010/resources/profiler/{{profiler-id}}
Authorization: Bearer {{auth_token}}
