apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/eclipse-slm/slm/ui:{{ .Values.slm.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: KEYCLOAK_URL
              value: http://keycloak:{{.Values.slm.keycloak.port}}/auth
            - name: AWX_URL
              value: http://awx-web:{{.Values.slm.awx.port_http}}/
            - name: BASYX_AAS_GUI_URL
              value: http://{{.Values.slm.hostname}}:3000

          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 40
            periodSeconds: 90
            timeoutSeconds: 10


      restartPolicy: Always
