apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: {{.Values.slm.ui_port}}
      targetPort: 80