#! /bin/bash

set -m

mkdir -p /consul/init

CONSUL_MASTER_TOKEN_FILE="/consul/init/consul_master_token"
if [ -f "$CONSUL_MASTER_TOKEN_FILE" ]; then
  echo "Consul already initialized"
  CONSUL_MASTER_TOKEN=$(cat "$CONSUL_MASTER_TOKEN_FILE")
else
  if [ "$CONSUL_MASTER_TOKEN" = "AutoGenerated" ]; then
      echo "Generating random Consul master token"
      CONSUL_MASTER_TOKEN=$(pwgen -s -1 24)
      echo "$CONSUL_MASTER_TOKEN" > $CONSUL_MASTER_TOKEN_FILE
  else
      echo "Using Consul master token from environment variable '$CONSUL_MASTER_TOKEN'"
  fi
fi

echo "$CONSUL_MASTER_TOKEN" > /config/root/consul_master_token
echo "$CONSUL_MASTER_TOKEN" > /config/awx/consul_token
echo "$CONSUL_MASTER_TOKEN" > /config/resource_management/consul_token
echo "$CONSUL_MASTER_TOKEN" > /config/resource_management_init/consul_token
echo "$CONSUL_MASTER_TOKEN" > /config/service_management/consul_token
echo "$CONSUL_MASTER_TOKEN" > /config/notification_service/consul_token
CONSUL_CONFIG_FILE=/consul/config/basic_config.json
CONSUL_CONFIG=$(cat $CONSUL_CONFIG_FILE | jq -r ". | .acl.tokens.master = \"$CONSUL_MASTER_TOKEN\"")
echo "$CONSUL_CONFIG" > $CONSUL_CONFIG_FILE

if [[ -z "${CONSUL_ADVERTISE}" ]]; then
  CONSUL_ADVERTISE_CMD=""
else
  CONSUL_ADVERTISE_CMD="-advertise ${CONSUL_ADVERTISE}"
fi

consul agent -server -bootstrap-expect 1 -ui -bind=0.0.0.0 -client=0.0.0.0 $CONSUL_ADVERTISE_CMD -data-dir=/consul/data -config-dir=/consul/config &

fg %1
