# Service Management
service-management:
  scheme: http
  host: localhost
  port: 9020
  path: /service-management
  url: ${service-management.scheme}://${service-management.host}:${service-management.port}${service-management.path}
  init-directories:
  git-repos:
    urls: "https://github.com/FabOS-AI/fabos-slm-service-registry-content.git"
    clone-directory: tmp/
  api-key: your-service-management-api-key

# Spring
spring:
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        enabled: true
        acl-token: ${consul.acl-token}

### Consul
consul:
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: your-consul-acl-token
