apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  "keycloak-secret" ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $keycloakAdminPassword := (get $secretData "keycloak-admin-password") | default ("password" | b64enc) }}
  {{- $keycloakDefaultUserPassword := (get $secretData "keycloak-default-user-password") | default ("password" | b64enc) }}
  # Encoded value: echo -n 'secret'|base64
  keycloak-admin-password: {{ $keycloakAdminPassword }}
  keycloak-default-user-password: {{ $keycloakDefaultUserPassword }}