apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-database-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-database-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-database-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-database-config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config-awx-jwt-authenticator-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-config-awx-jwt-authenticator

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config-notification-service-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-config-notification-service

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config-resource-registry-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-config-resource-registry

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config-service-registry-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-config-service-registry

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-config-service-registry-init-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /data/keycloak-config-service-registry-init

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-database-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-database-data-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-database-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-database-config-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-config-awx-jwt-authenticator-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-config-awx-jwt-authenticator-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-config-notification-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-config-notification-service-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-config-resource-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-config-resource-registry-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-config-service-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-config-service-registry-pv

  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-config-service-registry-init-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: keycloak-config-service-registry-init-pv

  storageClassName: ""

---
