apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: external
      protocol: TCP
      port: {{ .Values.slm.keycloak.port}}
      targetPort: 8080