apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  "keycloak-secret" ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $keycloakAdminPassword := (get $secretData "keycloak-admin-password") | default (randAlphaNum 32 | b64enc) }}
  {{- $keycloakDefaultUserPassword := (get $secretData "keycloak-default-user-password") | default (randAlphaNum 32 | b64enc) }}

    {{ if .Values.use_default_password }}
      {{- $keycloakAdminPassword := (get $secretData "keycloak-admin-password") | default (.Values.default_password | quote | b64enc) }}
      {{- $keycloakDefaultUserPassword := (get $secretData "keycloak-default-user-password") | default (.Values.default_password | quote | b64enc) }}
    {{ end }}

  # Encoded value: echo -n 'secret'|base64
  keycloak-admin-password: {{ $keycloakAdminPassword }}
  keycloak-default-user-password: {{ $keycloakDefaultUserPassword }}