services:
  installer-api:
    image: ghcr.io/eclipse-slm/slm/installer-api:${SLM_VERSION}
    pull_policy: always
    restart: unless-stopped
    environment:
      INSTALLER_COMPOSE_PROJECT_NAME: eclipse-slm-installer
      INSTALL_DIRECTORY: ${INSTALL_DIRECTORY:-/opt/eclipse-slm}
      SLM_HOSTNAME: ${SLM_HOSTNAME:-}
      SLM_IP: ${SLM_IP:-}
      DEPLOYMENT_HOST_HOSTNAME: ${DEPLOYMENT_HOST_HOSTNAME:-localhost}
      DEPLOYMENT_HOST_USER: ${DEPLOYMENT_HOST_USER:-}
      DEPLOYMENT_HOST_PASSWORD: ${DEPLOYMENT_HOST_PASSWORD:-}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${INSTALL_DIRECTORY:-/opt/eclipse-slm}:/install"

  installer-ui:
    image: ghcr.io/eclipse-slm/slm/installer-ui:${SLM_VERSION}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - installer-api
    ports:
      - "6060:80"
