### Inputs
- name: "Assert inputs of 'vault/init | init_after_keycloak.yml'"
  ansible.builtin.assert:
    that:
      - (vault.url.internal is defined) and (vault.url.internal|length > 0)                   # URL of the Vault instance
      - (ENV.VAULT.SCHEME.INTERNAL is defined) and (ENV.VAULT.SCHEME.INTERNAL|length > 0)     # Scheme of the Vault instance
      - (ENV.VAULT.HOST.INTERNAL is defined) and (ENV.VAULT.HOST.INTERNAL|length > 0)         # Host of the Vault instance
      - (ENV.VAULT.PORT.INTERNAL is defined)                                                  # Port of the Vault instance
      - (_vault_root_token is defined) and (_vault_root_token|length > 0)                     # Root token to authenticate with Vault
      - (keycloak.url.external_without_port is defined) and (keycloak.url.external_without_port|length > 0) # External URL of Keycloak without port (required for OIDC discovery URL)
      - (ENV.KEYCLOAK.REALM is defined) and (ENV.KEYCLOAK.REALM|length > 0)                   # Keycloak realm (required for OIDC discovery URL)

- name: "Store config"
  block:
    - ansible.builtin.set_fact:
        vault_config_consul:

    - ansible.builtin.import_role:
        name: eclipse-slm.consul_client
        tasks_from: create_or_add_config
      vars:
        _config:
          scheme: "{{ ENV.VAULT.SCHEME.INTERNAL }}"
          host: "{{ ENV.VAULT.HOST.INTERNAL }}"
          port: "{{ ENV.VAULT.PORT.INTERNAL }}"
          tokens:
            root: "{{ _vault_root_token }}"

- name: "Register Vault instance at Consul (discovery server)"
  ansible.builtin.include_role:
    name: eclipse-slm.consul_client
    tasks_from: register_service
  vars:
    _service_name: vault
    _service_port: "{{ ENV.VAULT.PORT.INTERNAL }}"
    _service_address: "{{ ENV.VAULT.HOST.INTERNAL }}"
    _http: "{{ vault.url.internal }}/v1/sys/health"
    _additional_tags:
      - "vault"

- name: "Configure JWT auth via Keycloak"
  ansible.builtin.import_role:
    name: eclipse-slm.vault_client
    tasks_from: configure_keycloak_jwt_auth_method
  vars:
    _vault_token: "{{ _vault_root_token }}"
    _mount_auth_path: "jwt"
    _oidc_discovery_url: "{{ keycloak.url.external_without_port }}/realms/{{ ENV.KEYCLOAK.REALM }}"
