---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true # Disable if your role does not rely on facts
  become: true
  pre_tasks:
    - name: Include env role from eclipse.slm collection
      ansible.builtin.include_role:
        name: eclipse.slm.env
        tasks_from: "{{ item }}"
      with_items:
        - main
        - write_hosts

    - name: Apply roles
      ansible.builtin.include_role:
        name: "{{ item.role }}"
        tasks_from: "{{ item.tasks_from | default('main') }}"
      vars:
        _consul_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
        _store_compose_dir: "/install/deployment"
        _vault_root_token: "{{ vault_root_token | default('') }}"
      loop:
        - role: ../../../vault
        - role: ../../../consul
          tasks_from: start
        - role: ../../../traefik
        - role: ../../../keycloak
        - role: ../../../minio
  tasks:
    - name: Apply role under test
      ansible.builtin.include_role:
        name: ../../../awx
      vars:
        _consul_token: "{{ ENV.CONSUL.MASTER_TOKEN }}"
        _vault_token: "{{ vault_root_token }}"
        _store_compose_dir: "/install/deployment"
