package org.eclipse.slm.service_management.features.service_offerings.impl.serviceofferingversions;

import io.swagger.v3.oas.annotations.tags.Tag;
import org.eclipse.slm.common.minio.model.exceptions.*;
import org.eclipse.slm.common.restserver.annotations.AuthorizedAsSlmUserOrApiKey;
import org.eclipse.slm.common.utils.objectmapper.ObjectMapperUtils;
import org.eclipse.slm.service_management.features.service_offerings.api.offeringversions.ServiceOfferingVersionsRestApi;
import org.eclipse.slm.service_management.features.service_offerings.api.offeringversions.ServiceOfferingVersionsRestApiConfig;
import org.eclipse.slm.service_management.features.service_offerings.api.offeringversions.ServiceOfferingVersionDTOApi;
import org.eclipse.slm.service_management.features.service_offerings.api.offerings.exceptions.ServiceOfferingNotFoundException;
import org.eclipse.slm.service_management.features.service_offerings.api.offerings.exceptions.ServiceOfferingVersionCreateException;
import org.eclipse.slm.service_management.features.service_offerings.api.offerings.exceptions.ServiceOfferingVersionNotFoundException;
import org.eclipse.slm.service_management.features.service_offerings.api.offerings.ServiceRequirement;
import org.eclipse.slm.service_management.features.service_offerings.api.offerings.responses.ServiceOfferingVersionCreateResponse;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping(ServiceOfferingVersionsRestApiConfig.BASE_PATH)
@Tag(name = ServiceOfferingVersionsRestApiConfig.TAG)
@AuthorizedAsSlmUserOrApiKey
public class ServiceOfferingVersionsRestController implements ServiceOfferingVersionsRestApi {


    private final ServiceOfferingVersionHandler serviceOfferingVersionHandler;

    public ServiceOfferingVersionsRestController(
            ServiceOfferingVersionHandler serviceOfferingVersionHandler) {
        this.serviceOfferingVersionHandler = serviceOfferingVersionHandler;
    }

    @Override
    public ResponseEntity<List<ServiceOfferingVersionDTOApi>> getServiceOfferingVersionsOfServiceOffering(
            UUID serviceOfferingId
    ) throws ServiceOfferingNotFoundException {
        var serviceOfferingVersions = this.serviceOfferingVersionHandler
                .getServiceOfferingVersionsOfServiceOffering(serviceOfferingId);

        var serviceOfferingVersionsDTOApi = ObjectMapperUtils
                .mapAll(serviceOfferingVersions, ServiceOfferingVersionDTOApi.class);

        return ResponseEntity.ok(serviceOfferingVersionsDTOApi);
    }

    @Override
    public ResponseEntity<ServiceOfferingVersionDTOApi> getServiceOfferingVersionById(
            UUID serviceOfferingId,
            UUID serviceOfferingVersionId) throws ServiceOfferingNotFoundException, ServiceOfferingVersionNotFoundException {
        var serviceOfferingVersion = this.serviceOfferingVersionHandler
                .getServiceOfferingVersionById(serviceOfferingId, serviceOfferingVersionId);

        var serviceOfferingVersionDTOApi = ObjectMapperUtils
                .map(serviceOfferingVersion, ServiceOfferingVersionDTOApi.class);

        return ResponseEntity.ok(serviceOfferingVersionDTOApi);
    }

    @Override
    public ResponseEntity<List<ServiceRequirement>> getServiceOfferingVersionRequirementsById(
            UUID serviceOfferingId,
            UUID serviceOfferingVersionId) throws ServiceOfferingNotFoundException, ServiceOfferingVersionNotFoundException {
        var serviceOfferingVersion = this.serviceOfferingVersionHandler
                .getServiceOfferingVersionById(serviceOfferingId, serviceOfferingVersionId);

        return ResponseEntity.ok(serviceOfferingVersion.getServiceRequirements());
    }

    @Override
    public @ResponseBody ResponseEntity<Void> createOrUpdateServiceOfferingVersionRequirementsWithId(
            UUID serviceOfferingId,
            UUID serviceOfferingVersionId,
            List<ServiceRequirement> requirements) throws ServiceOfferingNotFoundException, ServiceOfferingVersionNotFoundException {
        var serviceOfferingVersion = this.serviceOfferingVersionHandler
                .getServiceOfferingVersionById(serviceOfferingId, serviceOfferingVersionId);
        serviceOfferingVersion.setServiceRequirements(requirements);

        return new ResponseEntity<>(HttpStatus.OK);
    }

    @Override
    public ResponseEntity<ServiceOfferingVersionCreateResponse> createServiceOfferingVersionWithAutoGeneratedId(
            UUID serviceOfferingId,
            ServiceOfferingVersionDTOApi serviceOfferingVersionDTOApi)
            throws ServiceOfferingNotFoundException, ServiceOfferingVersionCreateException {

        serviceOfferingVersionDTOApi.setServiceOfferingId(serviceOfferingId);
        var serviceOfferingVersion = this.serviceOfferingVersionHandler
                .createServiceOfferingVersionWithAutoGeneratedId(serviceOfferingVersionDTOApi);

        return ResponseEntity.ok(new ServiceOfferingVersionCreateResponse(serviceOfferingVersion));
    }

    @Override
    public ResponseEntity<ServiceOfferingVersionCreateResponse> createOrUpdateServiceOfferingVersionWithId(
            UUID serviceOfferingId,
            UUID serviceOfferingVersionId,
            ServiceOfferingVersionDTOApi serviceOfferingVersionDTOApi)
            throws ServiceOfferingNotFoundException, ServiceOfferingVersionCreateException {

        serviceOfferingVersionDTOApi.setServiceOfferingId(serviceOfferingId);
        serviceOfferingVersionDTOApi.setId(serviceOfferingVersionId);
        var serviceOfferingVersion = this.serviceOfferingVersionHandler
                .createOrUpdateServiceOfferingVersionWithId(serviceOfferingVersionDTOApi);

        return ResponseEntity.ok(new ServiceOfferingVersionCreateResponse(serviceOfferingVersion));
    }

    @Override
    public @ResponseBody ResponseEntity<Void> deleteServiceOfferingVersion(UUID serviceOfferingId, UUID serviceOfferingVersionId)
            throws ServiceOfferingNotFoundException, ServiceOfferingVersionNotFoundException {
        this.serviceOfferingVersionHandler.deleteServiceOfferingVersionById(serviceOfferingId, serviceOfferingVersionId);
        return ResponseEntity.ok().build();
    }


    @Override
    public ResponseEntity<Void> createOrUpdateServiceOfferingFileWithId(UUID serviceOfferingId, UUID serviceOfferingVersionId, MultipartFile file)
            throws ServiceOfferingNotFoundException, ServiceOfferingVersionNotFoundException, MinioUploadException, MinioBucketCreateException,
            MinioRemoveObjectException, MinioObjectPathNameException, MinioBucketNameException {

        this.serviceOfferingVersionHandler
                .createOrUpdateServiceOfferingFile(serviceOfferingId, serviceOfferingVersionId, file);

        return ResponseEntity.ok().build();
    }

    @Override
    public ResponseEntity<InputStreamResource> getServiceOfferingFileWithId(UUID serviceOfferingId, UUID serviceOfferingVersionId, String fileName)
            throws Exception {

        var result = this.serviceOfferingVersionHandler
                .getServiceOfferingFile(serviceOfferingId, serviceOfferingVersionId, fileName);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=" + result.getFileName())
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_OCTET_STREAM_VALUE).body(new InputStreamResource(result.getFileStream()));
    }

}

