# Definition of realm: https://www.keycloak.org/docs-api/22.0.1/rest-api/index.html#RealmRepresentation
keycloak_config:
  database:
    host: keycloak-database
    url_host: keycloak-database
    schema: keycloak
    username: keycloak
    password: ''
    root_password: ''
  http:
    relative_path: /auth

keycloak_realms:
  - realm: "fabos"
    displayName: ""
    displayNameHtml: ""
    enabled: true
    loginTheme: "fabos"
    accessTokenLifespan: 86400

keycloak_realm: fabos

keycloak_groups_top_level:
  - name: users
    description: "Parent group for all users"
  - name: userGroups
    description: "Parent group for all user groups"
  - name: backendServices
    description: "Parent group for all backend services"

keycloak_realm_roles:
  - name: slm-user
    isDefault: true
  - name: slm-admin
    isDefault: false

keycloak_default_user:
  username: fabos
  firstName: Eclipse
  lastName: SLM
  email: info@fab-os.org
  enabled: true
  credentials:
    - type: password
      value: password
      temporary: false
  realmRoles: [ "slm-user", "slm-admin" ]
